### ISSUE TITLE
Add history field to it locale

### ISSUE THREAD

**Issue by cipparello** [two-pack/redmine_xls_export#1]
Hi two-pack,
    here there is a patch for the it locale with the new history field translated.

Thanks for all your efforts.
bye

<pre><code>
diff --git a/config/locales/it.yml b/config/locales/it.yml
--- a/config/locales/it.yml
+++ b/config/locales/it.yml
@@ -2,6 +2,7 @@ it:
   label_plugin_xlse_relations: "Esporta relazioni"
   label_plugin_xlse_watchers: "Esporta osservatori"
   label_plugin_xlse_description: "Esporta descrizione"
+  label_plugin_xlse_history: "Esporta storia"
   label_plugin_xlse_time: "Esporta tempo impiegato"
   label_plugin_xlse_attachments: "Elenco allegati"
   label_plugin_xlse_query_columns_only: "Esporta solo le colonne selezionate"
@@ -22,3 +23,6 @@ it:
   label_plugin_xlse_export_format_quick_tooltip: "Esporta utilizzando impostazioni predefinite"
   label_plugin_xlse_export_format_detailed: "Dettagliato"
   label_plugin_xlse_export_format_detailed_tooltip: "Seleziona opzioni prima di esportare"
+  
+  field_history: "Storia"
+

</code></pre>

**Comment by two-pack** [comment]
Hi cipparello,

I pushed your translations to repository.
https://github.com/two-pack/redmine_xls_export/commit/42588e53348d2a6a1aed578912c89b581f120228

Thank you for your help :)
