### ISSUE TITLE
Specify cell format for date & time.

### ISSUE THREAD

**Issue by two-pack** [two-pack/redmine_xls_export#10]
Issues have a 4 date & time information, Created, Updated, Start date, Due date.
Created and Updated are datetime format(DD.MM.YYYY hh:mm:ss), others are date format(DD.MM.YYYY).

I want to specify format for above information because some location's commonly date format is different (ex. in Japan YYYY/MM/DD).

**Comment by two-pack** [comment]
I remade this feature which is different from master branch.

**Comment by cforce** [comment]
Ther sahlle be a helo about how format is used with examples

**Comment by two-pack** [comment]
> Ther sahlle be a helo about how format is used with examples

I thought this comment was related pull request of #36.
_default_XXX_format_ should be specified like en.yml.
