### ISSUE TITLE
redmine 2.2.- detailed export - missing template

### ISSUE THREAD

**Issue by cforce** [two-pack/redmine_xls_export#11]
When i cklick detailed export (Urls is http://redmine.de:3000/projects/bus/issues_xls_export) i get a "missing template" responding with 404

**Comment by two-pack** [comment]
Please check your installation with follow:
http://www.redmine.org/plugins/redmine_xls_export

and see http://www.redmine.org/boards/3/topics/11986?r=35390#message-35390

**Comment by cforce** [comment]
Ow. rtfm.. Thanks that helped a lot ;)
