### ISSUE TITLE
Error when i would export issues

### ISSUE THREAD

**Issue by mbalecr7** [two-pack/redmine_xls_export#110]
Hello,

I just install the plugin on my redmine ( version 3.2.0 )

But when i would like to export issue, they say : 

Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.

Thank you

**Comment by two-pack** [comment]
Please explain more information like
* Log when this errer.
* Your environment.
* How to reproduce it if you know.

**Comment by two-pack** [comment]
> Your environment.

See http://www.redmine.org/projects/redmine/wiki/Submissions#Submitting-a-Bug

**Comment by mbalecr7** [comment]
Environment:
  Redmine version                3.2.5.stable.16172
  Ruby version                   2.2.5-p319 (2016-04-26) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.3
  Mercurial                      3.7.3
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  redmine_xls_export             0.2.1
  redmine_plugin_views_revisions 0.0.1

the bug is when i click on "quick" for xls export the error will appeared

**Comment by two-pack** [comment]
You probably use original plugin.
Try this GitHub version.

**Comment by mbalecr7** [comment]
Ok it's seem's working , thank's for your help
