### ISSUE TITLE
Possible to add export zip package for 1 selected issue

### ISSUE THREAD

**Issue by excceed** [two-pack/redmine_xls_export#112]
hello @two-pack
First thanks bring us this great plugin. 
I would like ask you if it is possible to add this feature: only export 1 selected issue with attachment to a zip package.  As current each operation will export all issues.

thanks~ :)

**Comment by two-pack** [comment]
Sorry I don't plan to implement new feature in this plugin.
But welcome to contribute it by all :)

**Comment by two-pack** [comment]
This repository is archived. See #135.
