### ISSUE TITLE
Import from xls,csv

### ISSUE THREAD

**Issue by cforce** [two-pack/redmine_xls_export#12]
Would be great to import from xlsx or csv.

**Comment by two-pack** [comment]
Please write details of the feature.

NOTE: already some ticket import plugin like:
https://github.com/juno/redmine_importer

**Comment by cforce** [comment]
The plugin does not work however and i think it shall be conter part for this and therefore included also on issues view with this plugin.

Import shall allow create or update (define issue id column is necesarry) issues from xls(x) and csv files. Updating means creating commecnts on updates, same as duing it manually. Importig must check user rights of course. Every row in table is an issue. Mapping columns to fields is needed, used defined fields shall be supported.
Either import all to one tracker or allow to define a tracker column (better name than id).

Export shall allow html conversion for description field. Escaping for field values and separators must work.

Charset setting is necesarry, especially for import.

**Comment by cforce** [comment]
If you wann check for integrating existing code: 
https://github.com/zh/redmine_importer/network
+
https://github.com/vividtone/redmine_importer.git (utf8 charset enahancements)

**Comment by two-pack** [comment]
This repository is archived. See #135.
