### ISSUE TITLE
Can't install to Redmine 4.0.4

### ISSUE THREAD

**Issue by ryoji-takeuchi** [two-pack/redmine_xls_export#123]
redmine_xls_export can't install to Redmine 4.0.4 because this plugin use method which was removed from Rails 5.1 or later. Redmine 4.0 need to use Rails 5.2.

**Comment by two-pack** [comment]
Sorry late response ;(
I can run this plugin on Redmine 4.0.4.
How do you install this plugin? Please try features branch or version 0.2.1.t11.
https://github.com/two-pack/redmine_xls_export/releases/tag/0.2.1.t11

**Comment by ryoji-takeuchi** [comment]
Thank you for your comment.
I re-installed 0.2.1.t11. Then can install successfully. 
Maybe, I choose wrong version at last time,
