### ISSUE TITLE
de locale - utf8 without BOM

### ISSUE THREAD

**Issue by cforce** [two-pack/redmine_xls_export#13]
de:
  label_plugin_xlse_legend_0: "Spalteneinstellungen"
  label_plugin_xlse_legend_1: "Exporteinstellungen"
  label_plugin_xlse_legend_1a: "Datumsformat"
label_plugin_xlse_legend_2: "weiter Einstellungen"
  label_plugin_xlse_legend_2_disabled: "Extra options (install rubyzip gem to access them)"

  label_plugin_xlse_relations: "Ticketbeziehungen exportieren"
  label_plugin_xlse_watchers: "Beobachter exportieren"
  label_plugin_xlse_description: "Beschreibungen exportieren"
  label_plugin_xlse_journal: "Tickjournale exportieren"
  label_plugin_xlse_time: "Aufgewendete Zeit exportieren"
  label_plugin_xlse_attachments: "Anhänge auflisten"
  label_plugin_xlse_query_columns_only: "Nur ausgewählte Spalten exportieren"
  label_plugin_xlse_group: "Unterteilung durch Gruppeneigenschaften"
  label_plugin_xlse_generate_name: "Namen generieren"
  label_plugin_xlse_export_attached: "Anhänge exportieren"
  label_plugin_xlse_separate_journals: "Tickjournal je als eigene Dateie exportieren"
  label_plugin_xlse_issues_limit: "Ticket Export Obergrenze setzten"
  label_plugin_xlse_issues_limit_help: "0 - Standard verwenden"
  label_plugin_xlse_issues_offset: "Exportiere die ersten x Tickets nicht"
  label_plugin_xlse_export_name: "Dateiendung"

  label_plugin_xlse_settings_title: "Exportdetails"
  label_plugin_xlse_button_export: "Export"
  label_plugin_xlse_button_back: "Zu den Tickets"

  label_plugin_xlse_field_attachment: "Anhänge"
  label_plugin_xlse_field_journal: "Journal"

  label_plugin_xlse_export_format: "XLS Export:"
  label_plugin_xlse_export_format_quick: "Express Export"
  label_plugin_xlse_export_format_quick_tooltip: "Exportiere mit Standard Einstellungen"
  label_plugin_xlse_export_format_detailed: "Detailierter Export"
  label_plugin_xlse_export_format_detailed_tooltip: "Wähle Export Optionen"

  label_plugin_xlse_date_created: "Angelegt"
  label_plugin_xlse_date_updated: "Aktualisiert"
  label_plugin_xlse_date_start: "Beginn"
  label_plugin_xlse_date_due: "Abgabedatum"

**Comment by two-pack** [comment]
This issue's title is 'de locale - utf8 without BOM'.
What mean that?
I think de.yml has not BOM on feature branch.

If you want to contribute this de translation, please pull request for feature branch.

NOTE:
And please check following:
*\* 'Tickjournal' or 'Ticket journal' ?
*\* Why does your 'Ticketbeziehungen exportieren' remove '-' ?

**Comment by cforce** [comment]
pull request send
