### ISSUE TITLE
Hidden values for roles are exported 

### ISSUE THREAD

**Issue by dominch** [two-pack/redmine_xls_export#131]
I have two custom fields hidden for some roles. 
On tickets those fields are hidden, on queries You can force to see them but they are all empty. 
With this plugin those values can be revealed in export. All columns should be checked if they are available for user, 

I checked more things and right now journals with restricted values are exported too.

**Comment by two-pack** [comment]
Thank you for reporting.
But I cannot reproduce it. Can you write more information like followings?
https://github.com/two-pack/redmine_xlsx_format_issue_exporter/wiki/How-to-report-issue

**Comment by dominch** [comment]
Hello, 
I have this issue on redmine 3.3, to reproduce create custom field visible only for one role, 
then with user with this role create any issue, fill any data for that CF. Then edit its value to get journal. 
Now switch to different user with other role, list issue to check if custom field is missing (it should be). Try export and with this bug it should be listed as column and in journal log. If custom field is with filter property then You should be able to get it as blank column on queries. 

I already fixed this issue, both fixes are in file redmine_xls_export/lib/xls_export.rb, first about line 283: 
`if (c.custom_field.visible_by?(project))`

and for journals at line 111, changed from: 
`journal.details.each do |detail|`
to 
`journal.visible_details.each do |detail|`

I'm not sure if those are all needed changes but that fixed quick xls export, I'll test if there is anything else.

**Comment by two-pack** [comment]
I can reproduce it with following environment and options.

**Options**
 + Export journal entries 
 + Export journal entries to worksheets
 + Issues journals as separate files

**Environment**
~~~
$ ruby bin/about
sh: 1: darcs: not found
sh: 1: hg: not found
sh: 1: cvs: not found
sh: 1: bzr: not found
Environment:
  Redmine version                3.3.10.stable
  Ruby version                   2.4.10-p364 (2020-03-31) [x86_64-linux]
  Rails version                  4.2.11.1
  Environment                    production
  Database adapter               SQLite
SCM:
  Subversion                     1.13.0
  Git                            2.25.1
  Filesystem
Redmine plugins:
  redmine_xls_export             0.2.1.t11
~~~

NOTE: I used latest features branch of redmine_xls_export.

> I already fixed this issue, both fixes are in file redmine_xls_export/lib/xls_export.rb, first about line 283:

Cool!
But I don't have time to fix and test for other reason, so I think it will take more time to fix.

**Comment by two-pack** [comment]
@dominch , I try to fix this problem on [hidden_cf_by_roles branch](https://github.com/two-pack/redmine_xls_export/tree/hidden_cf_by_roles).
Can you check to fix your problem above branch?

**Comment by dominch** [comment]
hello 
I just checked it that branch and hidden values are visible :/ 
I made few changes for that, here it's diff: 

```
diff --git a/lib/xls_export.rb b/lib/xls_export.rb
index 5d284be..df0ffef 100644
--- a/lib/xls_export.rb
+++ b/lib/xls_export.rb
@@ -130,12 +130,12 @@ class XLS_JournalQueryColumn < XLS_QueryColumn
     journals = get_visible_journals(issue)
     journals.each do |journal|
       hist_str << "#{format_time(journal.created_on)} - #{journal.user.name}\n"
-      journal.details.each do |detail|
+      journal.visible_details.each do |detail|^M
         hist_str <<  " - #{show_detail(detail, true)}"
-        hist_str << "\n" unless detail == journal.details.last
+        hist_str << "\n" unless detail == journal.visible_details.last^M
       end
       if journal.notes?
-          hist_str << "\n" unless journal.details.empty?
+          hist_str << "\n" unless journal.visible_details.empty?^M
           hist_str << journal.notes.to_s
       end
       hist_str << "\n" unless journal == journals.last
@@ -302,7 +302,7 @@ module Redmine
           last_prj = project

           issue_columns.each_with_index do |c, j|
-            v = if c.is_a?(QueryCustomFieldColumn)
+            v = if c.is_a?(QueryCustomFieldColumn) && (c.custom_field.visible_by?(project))^M
               case c.custom_field.field_format
                 when "int"
                   begin
@@ -436,9 +436,9 @@ module Redmine
           row.replace []

           details=''
-          journal.details.each do |detail|
+          journal.visible_details.each do |detail|^M
             details <<  "#{show_detail(detail, true)}"
-            details << "\n" unless detail == journal.details.last
+            details << "\n" unless detail == journal.visible_details.last^M
           end
           details = strip_html(details, options)
           notes = strip_html(journal.notes? ? journal.notes.to_s : '', options)
@@ -640,7 +640,7 @@ module Redmine
         issues.each do |issue|
           journals = get_visible_journals(issue)
           journals.each do |journal|
-            journal.details.each do |detail|
+            journal.visible_details.each do |detail|^M
               if detail.prop_key == "status_id"
                 row = sheet.row(idx+1)
                 row.replace []

```

all journal.details needs to be replaced by journal.visible_details, 
and like I said for custom fields column I added additional condition: (c.custom_field.visible_by?(project))

I hope that this fixes this problem, I'm passing this to test team and hope they confirm.

**Comment by two-pack** [comment]
@dominch Thank you for checking the branch and showing diff.
I thought I could reproduce this problem, but maybe I cannot yet...
Please show **step by step** to reproduce it.

My steps are following. I think exporting result of **Journal Column** is the journals on issue page.
1. Install Redmine 3.3.10.
2. Create Project.
3. Add Users and assign to the project.
    * **admin** is administrator of Redmine, and Manager roles.
    * **developer** is Developer roles.
    * **reporter** is Reporter roles.
4. Add custom field for Issue and set it to the project.
    * **Format** is Text.
    * **Visble** is selected **to these roles only:** and check only **Manager**.
5. Log in by **admin**.
6. Create Issue and set custom field.
7. Edit custom field.
8. Export issues list by **Details** link of redmine_xls_export with following settings.
    ![capture1](https://user-images.githubusercontent.com/378981/94438206-c0da6000-01d9-11eb-8ade-b854fadd9456.png)
    The result has a column of custom field and a journal of editting custom field.
9. Logout and Login by **developer**.
10. Open the issue. **developer** cannot show and edit custom field.
11. Export issues list by **Details** link of redmine_xls_export with above settings.
      The result has **NOT** a column of custom field and a journal of editting custom field by **admin**.
12. Logout and Login by **reporter**.
13. Open the issue. **reporter** cannot show and edit custom field.
14. Export issues list by **Details** link of redmine_xls_export with above settings.
      The result has **NOT** a column of custom field and a journal of editting custom field by **admin**.

I want to know last steps of reproducing same of you.
If I can, I'll check and test your diff, and merge it :)

Thank you again for your contributing!

**Comment by dominch** [comment]
Hello, 
I spent some time today to test that on fresh instance (3.3.10) and this branch of plugin. I'm using 3.3.2 on production now with lot of plugins. Probably there were some changes since 3.3.2 because I could not get hidden custom field column on query like I do on prod, and also I could not get it on export. On prod my condition (from diff) is needed to hide column and I can get that column on query for low roles with blank values. 

For journals I was able to export hidden value. The only thing I selected is to export journal entries to worksheets, there is still that value hidden for role on that tab. 

I think You can reproduce issue with that additional option selected (export journals to worksheets), also You can try 3.3.2 version (the one from my prod) - maybe this particular version has some bugs for columns functions so it displays them (but leave empty for unauthorized users). I know I need to upgrade this version to something fresh.

**Comment by two-pack** [comment]
@dominch , 
Thank you for researching this problem details.
I could reproduce it on trunk of Redmine, with option of **export journals to worksheets** and editing custom field with adding note.
I agree your diff **except** a line included *custom_field.visible_by* and committed them on the branch.
I think column exporting is good on current version of Redmine and 3.3.10 (are you same opinion?), so I think not to need the fix for column exporting. (I cannot prepare v3.3.2, so not checked on it.) 

NOTE: This plugin is checked and support current versions(NOT include 3.3.x, 3.3.2) of Redmine now.

**Comment by dominch** [comment]
Hello, 
Thanks for quick response and merging changes, I hope that will help others :) 
I know I need to upgrade redmine to current version, it's very big instance and I hope to move it to k8s, that takes some time. Right now I needed to leave my fix for custom field column on my instance. I will retest everything when it will be upgaded. 

Thanks again :)

**Comment by two-pack** [comment]
@dominch , Thank you for contributing a lot!
I merge it to features branch.
