### ISSUE TITLE
Invalid zip file with QUICK link.

### ISSUE THREAD

**Issue by two-pack** [two-pack/redmine_xls_export#15]
This problem reported http://www.redmine.org/boards/3/topics/11986?r=35564#message-35564 .
Exported zip file with QUICK link is XLS file in the fact. (changed file extension to check).

**Comment by cforce** [comment]
The exported zip file extracts a file named "Workbook" withiut any extension and non readable. If i rename the file to Workbook.xlsx excle complains in don't know the format and if i rename it to "Workbook.xls" Excel repirts major security problem and proposes not to open file because of trojan security risk!!!!!

Please fix or remove that intruder code, if any.

**Comment by cforce** [comment]
You have to rename the zip file to anything with .xls extension or configure extension in settings.
However this behavours is strange at however the user configures extension or not the file ending shall be save to *.xls if not part of the configured settings string.

**Comment by two-pack** [comment]
Please report followings:
- How to re-procedure this problem.
- Your environment with official board. (Including Excel version)
- Image of reporting major security from Excel. (Unfortunately, I have NOT Excel...)

**Comment by two-pack** [comment]
Official board comment:
http://www.redmine.org/boards/3/topics/11986?r=35675#message-35675

Usually  "(install rubyzip gem to access them)" on settings view is shown only when rubyzip is NOT installed.
But its first action when server run, this message was shown on admin settings.
This problem was fixed abobe commit.

But invalid zip problem is not fixed yet.

**Comment by two-pack** [comment]
I arrange this issues researching from official board.
- Exported zip file with pressing on the "QUICK" button isn't able to open on Windows.<br/>
  First reporting is on http://www.redmine.org/boards/3/topics/11986?r=35564#message-35564 .
- Environment  is reported on http://www.redmine.org/boards/3/topics/11986?r=35631#message-35631 .
- Exported zip is attached on http://www.redmine.org/boards/3/topics/11986?r=35631#message-35631 .
- Exported zip's content is xls file. We can rename file extension and check it.
- This plugin settings are http://www.redmine.org/attachments/download/8859/issues%20xls%20export%20settings.tiff .<br/>
- "(install rubyzip gem to access them)" on settings view with rubyzip. This problem fixed by 6faad68 .
- Gem list are http://www.redmine.org/boards/3/topics/11986?r=35675#message-35675 .

**Comment by two-pack** [comment]
I reprocedured this issue with Redmine DMSF Plugin on BitNami Redmine for Windows.
I put following logger into export_to_string() of xls_export_controller.rb.

```
logger.debug "defined?(Zip::ZipOutputStream::write_buffer): #{defined?(Zip::ZipOutputStream::write_buffer)}"
```

#{defined?(Zip::ZipOutputStream::write_buffer)} is "method", but It is null with Redmine DMSF Plugin.
This condition causes the issue because following sentence on the method.

```
return issues_xls unless export_name[1] == 'zip' && defined?(Zip::ZipOutputStream::write_buffer)
```

I'll check where conflict both plugins.

**Comment by two-pack** [comment]
'zip' and 'rubyzip' libraries conflict causes this problem.
Redmine DMSF Plugin needs 'zip' library, then added it in Gemfile.
Otherwise XLS Export Plugin needs 'rubyzip', but 'require' find 'zip' library. 'zip' has NOT Zip::ZipOutputStream::write_buffer.

I could Quick export after followings:
1. Uninstall 'zip' library using gem command.
2. I did rewrite 'zip' to 'rubyzip' on Gemfile of Redmine DMSF Plugin.
3. Re run bundle install.
4. Restart redmine.

NOTE: I did NOT check to work Redmine DMSF Plugin after above.

**Comment by two-pack** [comment]
Many zip libraries are on RubyGems.org now.
http://rubygems.org/search?utf8=%E2%9C%93&query=zip

'rubyzip' is the most downloaded and latest updated.
Because I'll request Redmine DMSF Plugin to change 'zip' library to 'rubyzip'.

**Comment by two-pack** [comment]
I pull-requested Redmine DMSF Plugin.
https://github.com/danmunn/redmine_dmsf/pull/110

If you wanna avoid this issue now, please try following:
1. "zip" to "rubyzip" on DSMF Plugin's Gemfile.
2. bundle install again and uninstall 'zip' gem like
$ bundle install
$ sudo gem uninstall zip
3. Restart redmine.
