### ISSUE TITLE
swtich Gemfile from http -> https ruby gems to quelch warning

### ISSUE THREAD

**Issue by shadowbq** [two-pack/redmine_xls_export#21]
In the Gemfile

source :rubygems

-to-

source 'https://rubygems.org'

**Comment by shadowbq** [comment]
`The source :rubygems is deprecated because HTTP requests are insecure.
Please change your source to 'https://rubygems.org' if possible, or 'http://rubygems.org' if not.`

**Comment by two-pack** [comment]
Thanks for your help :)
