### ISSUE TITLE
Iconv::InvalidEncoding (invalid encoding ("UTF-16LE//TRANSLIT//IGNORE", "UTF-8"))

### ISSUE THREAD

**Issue by fred-meng** [two-pack/redmine_xls_export#23]
ruby : 1.8.7
spreadsheet: 0.8.5
platform: windows 7
installer: bitnami-redmine-2.0.3-1-windows-installer-r01.exe

I have installed xls_export plugin for redmine, but every time I try exporting an Excel sheet of Issue list, I get the following error:

Iconv::InvalidEncoding (invalid encoding ("UTF-16LE//TRANSLIT//IGNORE", "UTF-8")):
spreadsheet (0.8.5) lib/spreadsheet/encodings.rb:38:in initialize'
spreadsheet (0.8.5) lib/spreadsheet/encodings.rb:38:innew'
spreadsheet (0.8.5) lib/spreadsheet/encodings.rb:38:in internal'
spreadsheet (0.8.5) lib/spreadsheet/excel/writer/biff8.rb:43:in_unicode_string'
spreadsheet (0.8.5) lib/spreadsheet/excel/writer/biff8.rb:36:in unicode_string'
spreadsheet (0.8.5) lib/spreadsheet/excel/writer/workbook.rb:353:inwrite_font'
spreadsheet (0.8.5) lib/spreadsheet/excel/writer/workbook.rb:362:in write_fonts'
spreadsheet (0.8.5) lib/spreadsheet/excel/writer/workbook.rb:359:ineach'
spreadsheet (0.8.5) lib/spreadsheet/excel/writer/workbook.rb:359:in write_fonts'
spreadsheet (0.8.5) lib/spreadsheet/excel/writer/workbook.rb:429:inwrite_from_scratch'
spreadsheet (0.8.5) lib/spreadsheet/excel/writer/workbook.rb:644:in write_workbook'
spreadsheet (0.8.5) lib/spreadsheet/writer.rb:12:inwrite'
spreadsheet (0.8.5) lib/spreadsheet/workbook.rb:124:in write'
plugins/redmine_xls_export/lib/xls_export.rb:275:inissues_to_xls2'
plugins/redmine_xls_export/app/controllers/xls_export_controller.rb:116:in export_to_string'
plugins/redmine_xls_export/app/controllers/xls_export_controller.rb:50:inexport_current'

**Comment by two-pack** [comment]
Could you tell me how to re-procedure, issues information, and something you know?
Not enough information for researching.

**Comment by fred-meng** [comment]
I have followed steps that described in plugin's installation instruction that 
1. installed bitnami installer (bitnami-redmine-2.0.3-1-windows-installer-r01.exe);
2. download spreadsheet0.8.5, ruby-ole-1.2.11.6 and rubyzip0.99 , installed them on local server(windows 7);
3. unzip the plugins (redmine_xls_export 0.2.1.t2 and redmine_plugin_views_revisions_v001) to redmine's plugins folder;
4. run command "bundle install --local" in redmine folder;
5. rake redmine:plugins:migrate RAILS_ENV=production and rake redmine:plugins:process_version_change RAILS_ENV=production

**Comment by two-pack** [comment]
I need more informations.
I think iconv error was occured by character code or related things.
1. your language in browser and redmine setting.
2. registered issues list. for examples, subjects, descriptions, and more.

**Comment by fred-meng** [comment]
1. Simple-Chinese both
2. just a test issue. all of them are several english letters.

**Comment by two-pack** [comment]
Not re-procedured on OS X 10.7.5.

**Comment by two-pack** [comment]
I checked on Windows 7 Pro 64bit Japanese with BitNami Redmine stack.
But not re-procedured yet.

Environment:
  Redmine version                          2.2.2.stable
  Ruby version                             1.9.3 (i386-mingw32)
  Rails version                            3.2.11
  Environment                              production
  Database adapter                         Mysql2
Redmine plugins:
  redmine_plugin_views_revisions           0.0.1
  redmine_xls_export                       0.2.1.t2

Any other informations how to re-procedure?

**Comment by fred-meng** [comment]
My environment:
redmine 2.0.3
ruby 1.8.7

**Comment by two-pack** [comment]
> spreadsheet (0.8.5) lib/spreadsheet/encodings.rb:38:in initialize'

The line is in the following method:

>    def internal string, client=Spreadsheet.client_encoding
>        string = string.dup
>        key = ['UTF-16LE', client]
>        iconv = @@iconvs[key] ||= Iconv.new('UTF-16LE//TRANSLIT//IGNORE', client)
>        iconv.iconv string
>    end

The method means only to convert utf-8 to utf-16LE with iconv.
I think 'string' from Redmine database, and you use BitNami Redmine Stack, so its encoding is utf-8.
Your error message indicates too.

I think this issues by iconv with environment.
NOTE: http://stackoverflow.com/questions/4965796/convert-utf-8-to-unicode-in-ruby

If you can update the redmine stack, you resolve this issue after updating.
If you want other action, please check followings:
1) What are 'string' and 'client' in above method?
2) In your environment(Bitnami Redmine Stack), please check these with logger and redmine's log.
