### ISSUE TITLE
NoMethodError (undefined method `plugin_redmine_xls_export' for #<Class:0xb4ce2548>)

### ISSUE THREAD

**Issue by fidelpd** [two-pack/redmine_xls_export#24]
I have a problem after install redmine xls export plugin. The installation process is correct but when I am going to access to the plugin configuration page I get this error:
NoMethodError (undefined method `plugin_redmine_xls_export' for #<Class:0xb4ce2548>):
app/controllers/settings_controller.rb:68:in`send'
app/controllers/settings_controller.rb:68:in `plugin_without_banner_date_validation'

I have been searching something on the Internet but I don´t find anything. Could you help me?

I am using redmine 2.3.1 and I have installed it in an Ubuntu 12.04.2 LTS. My RubyGems Enviroment is:
- RUBYGEMS VERSION: 1.8.15
- RUBY VERSION: 1.8.7 (2011-06-30 patchlevel 352) [i686-linux]
- INSTALLATION DIRECTORY: /var/lib/gems/1.8
- RUBY EXECUTABLE: /usr/bin/ruby1.8
- EXECUTABLE DIRECTORY: /usr/local/bin
- RUBYGEMS PLATFORMS:
  - ruby
  - x86-linux
- GEM PATHS:
  - /var/lib/gems/1.8
  - /home/evalues/.gem/ruby/1.8
- GEM CONFIGURATION:
  - :update_sources => true
  - :verbose => true
  - :benchmark => false
  - :backtrace => false
  - :bulk_threshold => 1000
- REMOTE SOURCES:
  - http://rubygems.org/

My gem list is:

```
ace (0.4.9)
actionmailer (3.2.13)
actionpack (3.2.13)
activemodel (3.2.13)
activerecord (3.2.13)
activeresource (3.2.13)
activesupport (3.2.13)
arel (3.0.2)
best_in_place (2.1.0)
builder (3.0.0)
bundler (1.3.5)
coderay (1.0.9)
daemon_controller (1.1.4)
dispatcher (0.0.1)
erubis (2.7.0)
factory_girl (2.6.0)
fastercsv (1.5.5)
haml (4.0.3)
hike (1.2.3)
i18n (0.6.1)
journey (1.0.4)
jquery-rails (2.0.3)
json (1.8.0)
mail (2.5.4)
mime-types (1.23)
mini_portile (0.5.0)
multi_json (1.7.6)
mysql (2.8.1)
net-ldap (0.3.1)
nokogiri (1.5.10, 1.5.6)
passenger (4.0.5)
polyglot (0.3.3)
rack (1.4.5)
rack-cache (1.2)
rack-openid (1.3.1)
rack-ssl (1.3.3)
rack-test (0.6.2)
rails (3.2.13)
railties (3.2.13)
rake (10.0.4)
rdoc (4.0.1, 3.12.2)
rdoc-data (4.0.1)
ri_cal (0.8.8)
rmagick (2.13.2)
ruby-ole (1.2.11.6)
ruby-openid (2.1.8)
rubyzip (0.9.9)
rufus-scheduler (2.0.19)
simple_enum (1.6.5)
spreadsheet (0.8.5)
sprockets (2.2.2)
template-inheritance (0.3.1)
thor (0.18.1)
tilt (1.4.1)
treetop (1.4.14)
tzinfo (0.3.37)
uuidtools (2.1.4)
webrat (0.7.3)
```

My redmine plugin list is:

```
Clipboard image paste (1.6)
Progressive Projects List plugin (0.4.0)
Redmine Apijs plugin (4.2.0)
Redmine Banner plugin (0.0.9)
Redmine Charts (0.2.1)
Redmine Custom Workflow plugin (0.0.4)
DMSF (1.4.5p1 stable)
Redmine EVM plugin (0.9.1)
Redmine Favourite Projects plugin (0.6.3)
Hide estimated hours (1.0.3)
Issue Importer (1.0)
Redmine Issue Checklist plugin (2.0.5)
Redmine Issue Templates plugin (0.0.5)
Redmine Light Box plugin (0.0.1)
Meetings plugin (0.2.3)
Redmine (Monitoring & Controlling | Monitoramento & Controle) (0.1.1)
Redmine plugin views revisions plugin (0.0.1)
Redmine Process Frameworks plugin (1.0.1)
Redmine Spent Time plugin (2.5.0)
Redmine Timesheet Plugin (0.7.0)
Time & Expense (1.5)
Redmine Work Time plugin (0.2.10)
Issues XLS export (0.2.1 t2)
Stuff To Do Plugin (0.5.1)
Timelog Timer plugin (2.0.0)
```

If you require any further information, feel free to contact me.

Thank you in advance.

**Comment by two-pack** [comment]
I couldn't re-procedure the issue with Redmine 2.3.1, Ruby 1.8.7 on OS X 10.7.5.

**Comment by two-pack** [comment]
Maybe no conflict of following plugins. I checked them on OS X.

> Clipboard image paste (1.6)
> Progressive Projects List plugin (0.4.0)
> Redmine Apijs plugin (4.2.0)
> Redmine Banner plugin (0.0.9)
> Redmine Charts (0.2.1)
> Redmine Custom Workflow plugin (0.0.4)
> DMSF (1.4.5p1 stable)
> Redmine EVM plugin (0.9.1)

**Comment by two-pack** [comment]
I checked followings on OS X.

> Redmine Favourite Projects plugin (0.6.3)
> Hide estimated hours (1.0.3)
> Issue Importer (1.0)
> Redmine Issue Checklist plugin (2.0.5)

**Comment by two-pack** [comment]
I could reprocedure this issue on my environment with Time & Expense plugin.

NOTE: Followings are not affected.

> Redmine Issue Templates plugin (0.0.5)
> Redmine Light Box plugin (0.0.1)
> Meetings plugin (0.2.3)
> Redmine (Monitoring & Controlling | Monitoramento & Controle) (0.1.1)
> Redmine plugin views revisions plugin (0.0.1)
> Redmine Process Frameworks plugin (1.0.1)
> Redmine Spent Time plugin (2.5.0)
> Redmine Timesheet Plugin (0.7.0)

**Comment by cforce** [comment]
Please fix, same here

**Comment by two-pack** [comment]
I think this issue is caused by Time & Expense plugin.
The plugin uses 'Setting' in init.rb, but it's probably not good practice on Rails.

I changed the plugin which is following patch for init.rb. I cannot check the plugin works fine, but NoMethodError is not appeared.

```
87a88
> Rails.configuration.to_prepare do
111a113
> end
n007:plugins twopack$ diff -u redmine_wktime/init.rb redmine_wktime_patch/init.rb 
--- redmine_wktime/init.rb  2013-03-05 16:29:37.000000000 +0900
+++ redmine_wktime_patch/init.rb    2013-06-29 22:17:56.000000000 +0900
@@ -85,6 +85,7 @@

 end

+Rails.configuration.to_prepare do
 if !Setting.plugin_redmine_wktime['wktime_nonsub_mail_notification'].blank? && Setting.plugin_redmine_wktime['wktime_nonsub_mail_notification'].to_i == 1
 require 'rufus/scheduler' 

@@ -109,6 +110,7 @@
        end
    end 
 end
+end

 class WktimeHook < Redmine::Hook::ViewListener
    def controller_timelog_edit_before_save(context={ })
```

See:
http://www.redmine.org/boards/3/topics/16587
http://stackoverflow.com/questions/12474851/setting-configuration-in-init-rb
http://www.redmine.org/boards/3/topics/31445#Overriding-models-controllers-and-helpers
