### ISSUE TITLE
Issue description column duplicated

### ISSUE THREAD

**Issue by dkmorgan** [two-pack/redmine_xls_export#26]
I'm using plugin rev. 0.2.1.t3 with redmine 2.3.1.
When I use the detailed export feature and check the issue description checkbox, the resulting excel file contains two issue description columns.
If I don't check the issue description checkbox, the resulting excel file still contains a description column.

**Comment by githubrs** [comment]
I have got the same problem. 
This is my Environment:
  Redmine version                2.3.2.stable
  Ruby version                   1.9.3-p194 (2012-04-20) [x86_64-linux]
  Rails version                  3.2.13
  Environment                    production
  Database adapter               PostgreSQL
Redmine plugins:
  extended_top_menu              0.0.1
  redmine_plugin_views_revisions 0.0.1
  redmine_xapian                 1.5.1
  redmine_xls_export             0.2.1.t3

**Comment by two-pack** [comment]
The feature which issues list shows descriptions was added Redmine 2.2.0.
See http://www.redmine.org/issues/3447 .

This problem causes above feature.

**Comment by two-pack** [comment]
Fixes description column is duplicated on Redmine version 2.2.0 or above.
https://github.com/two-pack/redmine_xls_export/commit/3c66b846e5d1a446713ae2ce2fe9bfad9cfec51b

But spent time column has same problem on Redmine version 1.4.0 or above.
See http://www.redmine.org/issues/971 .

And Id column has similar problem but maybe the reason is different.

**Comment by two-pack** [comment]
I fixed this problem by some commits.
I made a sense of the specification.
- We can export XLS file of issue list.
- We can select exported columns on issue list.
- We can select a description column if we cannot select it on issue list.
- We can select a spent time column if we cannot select it on issue list.
- We don't need settings for exporting description and spent time column if we can select them on issue list.

**Comment by two-pack** [comment]
When you use Redmine 1.3.x, you may have a error because the version doesn't have a following patch.
http://www.redmine.org/projects/redmine/repository/revisions/8276

**Comment by fengyedou** [comment]
Hi,

I know redmine has description option for issue list, but that needs to select each time when you want to export issues, the description option canot be fixed, if developer forgets to select from redmine option, it needs to export again.

But if the plug-in has the exported description option, it can be fixed during plug-in configuration. 
Is there any way to handle this request? I hope the description option can be fixed during some configuration, no need to select each time when exported.

Thanks.
