### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by githubrs** [two-pack/redmine_xls_export#27]
Hello

it would be really nice if someone can help me.
I wanted to install this plugin but the installation failed: I ran these commands in the terminal and did the following:
  cd /[remine_root]
  gem install spreadsheet
  gem install rubyzip
copied the "plugin views with revision"-plugin
  cd plugins

  rake redmine:plugins:migrate RAILS_ENV="production"
  /etc/init.d/apache2 restart

**Comment by two-pack** [comment]
You need to run following command after copying Plugin views with revisions and xls export plugin.

> rake redmine:plugins:process_version_change RAILS_ENV=production

Please re-check how to installation.
https://github.com/two-pack/redmine_xls_export#installation-and-setup

If you cannot install yet, please describe the details of your environment(ex. OS, Versions, ...).

**Comment by githubrs** [comment]
Sorry for my bad description of the issue but it seems that updating the comment failed.
At first my environment:
Debian 7.0
Environment:
  Redmine version                          2.3.1.stable
  Ruby version                             1.9.3 (x86_64-linux)
  Rails version                            3.2.13
  Environment                              production
  Database adapter                         PostgreSQL
Redmine plugins:
  extended_top_menu                        0.0.1
  redmine_plugin_views_revisions           0.0.1

So now to the problem and the real installation i did:
cd /[remine_root]
gem install spreadsheet
gem install rubyzip
copied the "plugin views with revision"-plugin
rake redmine:plugins:migrate RAILS_ENV="production"
/etc/init.d/apache2 restart

I think so far it worked. I can see the "plugin views with revision"-plugin in Administration-->Plugins
Now to the Installation of the "xls_export"-plugin
i copied the "xls_export"-plugin to /plugins
rake redmine:plugins:migrate RAILS_ENV="production"
rake redmine:plugins:process_version_change RAILS_ENV=production
/etc/init.d/apache2 restart

In my redmine directory all permissions are set to 777 so that shouldn't be the problem.
My bundle is also complete.
The folloing was written in the log-file:
"
Connecting to database specified by database.yml
OpenIdAuthentication.store is nil. Using in-memory store.
Creating scope :system. Overwriting existing method Enumeration.system.
Creating scope :sorted. Overwriting existing method Group.sorted.
Connecting to database specified by database.yml
OpenIdAuthentication.store is nil. Using in-memory store.
Creating scope :system. Overwriting existing method Enumeration.system.
"

Thank you for your fast answer and i hope you can help me with my problem

**Comment by githubrs** [comment]
P.S.
that's what i get in the browser:

Ruby on Rails application could not be started
These are the possible causes:

```
There may be a syntax error in the application's code. Please check for such errors and fix them.
A required library may not installed. Please install all libraries that this application requires.
The application may not be properly configured. Please check whether all configuration files are written correctly, fix any incorrect configurations, and restart this application.
A service that the application relies on (such as the database server or the Ferret search engine server) may not have been started. Please start that service.
```

Further information about the error may have been written to the application's log file. Please check it in order to analyse the problem.

Error message:
    /usr/local/share/redmine-2.3/app/models/setting.rb:136: syntax error, unexpected '-', expecting ';' or '\n' def self.plugin_redmine_xls_export-features ^ /usr/local/share/redmine-2.3/app/models/setting.rb:138: syntax error, unexpected keyword_end, expecting $end
Exception class:
    SyntaxError
Application root:
    /usr/local/share/redmine 
Backtrace:
    #   File    Line    Location
    0   /usr/local/share/redmine-2.3/app/models/setting.rb  136     in `class_eval'
    1   /usr/local/share/redmine-2.3/app/models/setting.rb  136     in`block in '
    2   /usr/local/share/redmine-2.3/app/models/setting.rb  122     in `each'
    3   /usr/local/share/redmine-2.3/app/models/setting.rb  122     in`'
    4   /usr/local/share/redmine-2.3/app/models/setting.rb  18  in `'
    5   /var/lib/gems/1.9.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb    251     in`require'
    6   /var/lib/gems/1.9.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb    251     in `block in require'
    7   /var/lib/gems/1.9.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb    236     in`load_dependency'
    8   /var/lib/gems/1.9.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb    251     in `require'
    9   /var/lib/gems/1.9.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb    359     in`require_or_load'
    10  /var/lib/gems/1.9.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb    313     in `depend_on'
    11  /var/lib/gems/1.9.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb    225     in`require_dependency'
    12  /var/lib/gems/1.9.1/gems/railties-3.2.13/lib/rails/engine.rb    439     in `block (2 levels) in eager_load!'
    13  /var/lib/gems/1.9.1/gems/railties-3.2.13/lib/rails/engine.rb    438     in`each'
    14  /var/lib/gems/1.9.1/gems/railties-3.2.13/lib/rails/engine.rb    438     in `block in eager_load!'
    15  /var/lib/gems/1.9.1/gems/railties-3.2.13/lib/rails/engine.rb    436     in`each'
    16  /var/lib/gems/1.9.1/gems/railties-3.2.13/lib/rails/engine.rb    436     in `eager_load!'
    17  /var/lib/gems/1.9.1/gems/railties-3.2.13/lib/rails/application/finisher.rb  53  in`block in '
    18  /var/lib/gems/1.9.1/gems/railties-3.2.13/lib/rails/initializable.rb     30  in `instance_exec'
    19  /var/lib/gems/1.9.1/gems/railties-3.2.13/lib/rails/initializable.rb     30  in`run'
    20  /var/lib/gems/1.9.1/gems/railties-3.2.13/lib/rails/initializable.rb     55  in `block in run_initializers'
    21  /var/lib/gems/1.9.1/gems/railties-3.2.13/lib/rails/initializable.rb     54  in`each'
    22  /var/lib/gems/1.9.1/gems/railties-3.2.13/lib/rails/initializable.rb     54  in `run_initializers'
    23  /var/lib/gems/1.9.1/gems/railties-3.2.13/lib/rails/application.rb   136     in`initialize!'
    24  /var/lib/gems/1.9.1/gems/railties-3.2.13/lib/rails/railtie/configurable.rb  30  in `method_missing'
    25  /usr/local/share/redmine-2.3/config/environment.rb  14  in`'
    26  /usr/lib/ruby/vendor_ruby/phusion_passenger/classic_rails/application_spawner.rb    222     in `require'
    27  /usr/lib/ruby/vendor_ruby/phusion_passenger/classic_rails/application_spawner.rb    222     in`preload_application'
    28  /usr/lib/ruby/vendor_ruby/phusion_passenger/classic_rails/application_spawner.rb    181     in `block in initialize_server'
    29  /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb    572     in`report_app_init_status'
    30  /usr/lib/ruby/vendor_ruby/phusion_passenger/classic_rails/application_spawner.rb    174     in `initialize_server'
    31  /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_server.rb  204     in`start_synchronously'
    32  /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_server.rb  180     in `start'
    33  /usr/lib/ruby/vendor_ruby/phusion_passenger/classic_rails/application_spawner.rb    149     in`start'
    34  /usr/lib/ruby/vendor_ruby/phusion_passenger/spawn_manager.rb    219     in `block (2 levels) in spawn_rails_application'
    35  /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_server_collection.rb   132     in`lookup_or_add'
    36  /usr/lib/ruby/vendor_ruby/phusion_passenger/spawn_manager.rb    214     in `block in spawn_rails_application'
    37  /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_server_collection.rb   82  in`block in synchronize'
    38      prelude>    10:in `synchronize'
    39  /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_server_collection.rb   79  in`synchronize'
    40  /usr/lib/ruby/vendor_ruby/phusion_passenger/spawn_manager.rb    213     in `spawn_rails_application'
    41  /usr/lib/ruby/vendor_ruby/phusion_passenger/spawn_manager.rb    132     in`spawn_application'
    42  /usr/lib/ruby/vendor_ruby/phusion_passenger/spawn_manager.rb    275     in `handle_spawn_application'
    43  /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_server.rb  357     in`server_main_loop'
    44  /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_server.rb  206     in `start_synchronously'
    45  /usr/share/phusion-passenger/helper-scripts/passenger-spawn-server  99  in`'

**Comment by two-pack** [comment]
If the folder name of redmine_xls_export is 'plugin_redmine_xls_export-features', please change the folder name of redmine_xls_export from 

> /usr/local/share/redmine-2.3/plugins/plugin_redmine_xls_export-features

to

> /usr/local/share/redmine-2.3/plugins/plugin_redmine_xls_export

**Comment by githubrs** [comment]
This solved my problem. Thank you very much for the fast help. You did a great job.
