### ISSUE TITLE
Long description can't be displayed correct

### ISSUE THREAD

**Issue by githubrs** [two-pack/redmine_xls_export#28]
Hello!

I like your plugin very much and it works also fine. There's only one little thing:
If the issues description is longer than 30 lines excel can't display it correct. Then it shows only a part of the description. For watching the whole description you have to edit the field. There is the same problem with to long comments and it's the same in the journal file. I would suggest splitting the description and comments(only if it's to long) in multiple rows with max. 25 lines in one field. The new rows could be named as for example #595a, #595b, ... The other informations like Project, Status, Priority, etc. could be simple copied to the new rows.

Here is an exported file where you can see this bug. It's a test-issue with your README-file as description and the GNU-license as comment.
http://www.file-upload.net/download-7848878/130717_Projects_issues_export.zip.html 

I hope you Understand my problem and maybe you can help me.
Thanks in advance

**Comment by two-pack** [comment]
I understand your opinion, but it's not a bug. It depends on our environment like display resolution, zoom size, and more.
And I think the description which has over 30 lines is (should be) a few case.

In your use case, why do you need issues description in exported xls?
If you don't need it, 'Export description' option should be off (but now the plugin has #26 :( ).

**Comment by githubrs** [comment]
Ok, i understand. But is there a possibility to implement a function, to set the maximum number of lines manually.

Thank you for your answer.
