### ISSUE TITLE
Detailed link is broken

### ISSUE THREAD

**Issue by okamototk** [two-pack/redmine_xls_export#29]
At Issues view, XLS export  'Detailed' link is broken. 
404 error occurs when I clicked 'Detailed' link.

**Comment by two-pack** [comment]
Please check your installation, especially run rake for redmine change revision plugin.
If you don't resolve the issue after that, please tell me your environment and more information to reprocedure it.

**Comment by okamototk** [comment]
Thanks for quickly reply. I tested on Redmine 2.3.1. Other functions are working. Just Detail link is not work.

regards

**Comment by two-pack** [comment]
Did you check your installation?
https://github.com/two-pack/redmine_xls_export#installation-and-setup

If you didn't following rake, 404 is occured because a html file wasn't created.

> rake redmine:plugins:process_version_change RAILS_ENV=production

**Comment by okamototk** [comment]
Sorry, I use rake redmine:plugin:migrate to install.

**Comment by googol4u** [comment]
I try to run:
rake redmine:plugins:process_version_change RAILS_ENV=production

and get this:

rake aborted!
Don't know how to build task 'redmine:plugins:process_version_change'

**Comment by two-pack** [comment]
What is version of the plugin and Redmine?(2.5.1 or other?)
And can you show more information like logs?

BTW this problem is like #29, but I closed #29 with invalid installation.
Please make new issue of your problem.

**Comment by indraveni** [comment]
Created New Issue at #64
https://github.com/two-pack/redmine_xls_export/issues/64
