### ISSUE TITLE
When using with 2.3 and click config or detailed export, resulting in 404 

### ISSUE THREAD

**Issue by googol4u** [two-pack/redmine_xls_export#35]
Thanks for your great effort to make this plugin working on 2.2 and 2.3 version of redmine. I am using it with 2.3 version.

When I click config under mangement->plugins or click the detailed export link.  A 404 shows up.

production.log shows the following message:

```
Started GET "/redmine/settings/plugin/redmine_xls_export" for 113.68.164.245 at Sat Sep 28 01:32:27 +0800 2013
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_xls_export"}
  Current user: admin (id=1)
  Rendered settings/plugin.html.erb within layouts/admin (2.6ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.5ms)
Completed 404 Not Found in 44ms (Views: 26.7ms | ActiveRecord: 0.3ms)
```

Any suggestions?

**Comment by two-pack** [comment]
See #29.

**Comment by two-pack** [comment]
> I try to run:
> rake redmine:plugins:process_version_change RAILS_ENV=production
> 
> and get this:
> 
> rake aborted!
> Don't know how to build task 'redmine:plugins:process_version_change'

Did you run the rake after 'Plugin views with revisions' installed?

**Comment by googol4u** [comment]
Sorry.  Because it is not listed in the "Requirements" section.  I have installed  'Plugin views with revisions' and solved the issue. Thank you very much!
