### ISSUE TITLE
Private Note are visible

### ISSUE THREAD

**Issue by davideraro** [two-pack/redmine_xls_export#37]
Private Note are visible when export is done by an user which cannot see the private note.

**Comment by two-pack** [comment]
Private note is http://www.redmine.org/issues/1554 .

**Comment by davideraro** [comment]
Thank you for you answer.. Last question, I'm sorry but I'm really new of redmine.. how to add those patch?
Thank in advance

**Comment by two-pack** [comment]
Thank you for your posting this issue. It is the plugin's issue.
I try to fix it, but need more time. I want to fix it by Milestone 0.2.1.t5.

**Comment by davideraro** [comment]
ok ;) Thank you and take your time. Please let me know when it will be done in order to update the plugin which is very heasy to use and very useful. Congrats

**Comment by cforce** [comment]
Yes please, waiting also for this ;)
