### ISSUE TITLE
when click detailed XLS export:Detailed at bottom of issues not working

### ISSUE THREAD

**Issue by johnp2686** [two-pack/redmine_xls_export#40]
Hello,

 I have using redmine 2.2.4 i installed redmine_xls_export plugin in issue bottom option quick and detailed ,quik options link is working but detailed option links in not working .any one help regarding this kind of issue 

Regards,

John Paul.D

**Comment by two-pack** [comment]
Please check your installation.
And more information of your issue.

**Comment by johnp2686** [comment]
Installtion is correct when click the detailed option hitting error (The page you were trying to access doesn't exist or has been removed.404 error)

**Comment by two-pack** [comment]
Please show more information.
1) Did you run following rake on installation?
rake redmine:plugins:process_version_change RAILS_ENV=production
2) Version of your this plugin.

**Comment by johnp2686** [comment]
i tried 
 rake redmine:plugins:process_version_change RAILS_ENV=production

but hitting error rake aborted!
Don't know how to build task 'redmine:plugins:process_version_change'

(See full trace by running task with --trace)

**Comment by two-pack** [comment]
Check how to install this plugin.
https://github.com/two-pack/redmine_xls_export#installation-and-setup

**Comment by johnp2686** [comment]
Your mention  Installation and Setup i did  but i ran this command
rake redmine:plugins:process_version_change RAILS_ENV=production hiting error can u help me for this

**Comment by two-pack** [comment]
Did you run it on 'redmine_xls_plugin' folder?
Please show the error on console.

**Comment by johnp2686** [comment]
## log file

XLS export controller: rubyzip gem not available
OpenIdAuthentication.store is nil. Using in-memory store.
Migrating to CreateNewissuealerts (1)
Migrating to AddPriorityToNewissuealerts (20110722141200)
Migrating to AlterNewissuealertsSetDefaults (20110722144500)
Migrating to AddTemplateToNewissuealerts (20120823125900)
Migrating to AddSubjectToNewissuealerts (20120823145100)
Migrating to AddTrackerToNewissuealerts (20120828162900)
Migrating to AlterTrackerDefault (20130315083900)
Connecting to database specified by database.yml

**Comment by two-pack** [comment]
The log has "rubyzip gem not found". Did you succes 'bundle install' on redmine_xls_export folder?

BTW please show commands, console log and path  when you show some information.
I donot know the log what you ran.

**Comment by johnp2686** [comment]
I have installed rubyzip gem and bundle installed successfully but again it getting error

**Comment by johnp2686** [comment]
I checkout master branch it is ok with  redmine 2.2.4

**Comment by two-pack** [comment]
Could you show your gem list and plugin list?
I think this issue is like #15 .

**Comment by johnp2686** [comment]
Thanks it is works

**Comment by two-pack** [comment]
It sounds good :)
Please show the reason of this issue, plugin name or something, if you can.
And can I close this issue?

**Comment by johnp2686** [comment]
The installation setup i didn't install  Plugin views with revisions that is the problem
