### ISSUE TITLE
When export issue it will not showing status to another status like(new to in progress)

### ISSUE THREAD

**Issue by johnp2686** [two-pack/redmine_xls_export#41]
Hello,

When export issue it will not showing status to another status like(new to in progress ,In progress to resolved ,resolved to closed)  for single issue ,any can help regarding problem

**Comment by two-pack** [comment]
The plugin exports issues list which is showed in Issues page.
Please add some information columns on Issues page.

Another solution, the plugin has a option which can export issues list with all columns.

**Comment by johnp2686** [comment]
I added issue list but  i need 
 issue_statuses old_status ON old_status.id = p.old_value
with journal_details

**Comment by two-pack** [comment]
Please take screen captures of Isses page and plugin settings pages.

**Comment by johnp2686** [comment]
I have attached screen shoot mysql query (what i need from this plugin) format as xls
i used sql query for this for format

SELECT u.id Ticket_ID, trackers.name Tracker, enum.name Priority, u.created_on, ug.created_on updated_on, old_status.name from_status,status.name to_status
FROM issues u 
JOIN trackers ON trackers.id=u.tracker_id
JOIN enumerations enum ON enum.id = u.priority_id
JOIN journals ug ON ug.journalized_id = u.id
JOIN journal_details p on p.journal_id = ug.id 
JOIN issue_statuses old_status ON old_status.id=p.old_value
JOIN issue_statuses status ON status.id=p.value
WHERE u.created_on between  "2013-12-01 00:00:00" and "2013-12-31 23:59:59" AND u.project_id="50" AND ug.journalized_type="issue" AND p.prop_key in (select journal_details.prop_key FROM journal_details WHERE journal_details.prop_key="status_id") 

Can u understand ? what i need from ur plugin and help me
![issues_format](https://f.cloud.github.com/assets/951104/1928973/c7585af2-7e8e-11e3-8909-83eb64f192cb.png)

**Comment by two-pack** [comment]
I understand you said, but the plugin hasn't it now.
I try to add it on the plugin, but I need enough time to implement it....

**Comment by two-pack** [comment]
Does 'Export journal entries' option of the plugin match you want?
You can export 'status to status' on 'Journal' column.

**Comment by johnp2686** [comment]
OK Thanks ,can u explain how to  export status to status on journal column

**Comment by two-pack** [comment]
> OK Thanks ,can u explain how to export status to status on journal column

Use [Columns options] -> [Export journal entries] option.
You can set detail export page or this option the plugin's setting page.

**Comment by two-pack** [comment]
see following:
![screen](https://f.cloud.github.com/assets/378981/2000616/17566d5e-8561-11e3-8df1-853ae7f963c1.png)

**Comment by johnp2686** [comment]
![journal_format](https://f.cloud.github.com/assets/951104/2039009/1b69f4ce-8999-11e3-869d-7262f1272156.png)

Hello ,

I get the journals entries for i asked but i get in issue journals as separate file ,i need all issue in single xls sheet how export single sheet all issue i will send u code and screen shot 

redmine_xls_export/lib/xls_export.rb

 def journal_details_to_xls(issue)
        issue_updates = issue.journals.all(:include => [:user, :details], :order => "#{Journal.table_name}.created_on ASC")
        return nil if issue_updates.size == 0

```
    Spreadsheet.client_encoding = 'UTF-8'
    book = Spreadsheet::Workbook.new
    sheet1 = book.create_worksheet(:name => "%05i - Journal" % [issue.id])

    columns_width = []
    sheet1.row(0).replace []
    ['#',l(:field_issue),l(:label_tracker),l(:field_priority),l(:field_created_on),l(:field_updated_on),l(:field_user),l(:field_status_from),l(:field_status_to)].each do |c|
      sheet1.row(0) << c
      columns_width << (get_value_width(c)*1.1)
    end
    sheet1.column(0).default_format = Spreadsheet::Format.new(:number_format => "0")

    idx=0
    issue_updates.each do |journal|
      row = sheet1.row(idx+1)
      row.replace []

      details=''
      journal.details.each do |detail|
        if detail.prop_key == 'status_id'
         [idx+1,issue.id,issue.tracker_id,issue.priority_id,issue.created_on,journal.created_on,journal.user.name,detail.old_value,detail.value].each_with_index do |e,e_idx|
            lf_pos = get_value_width(e)
            columns_width[e_idx] = lf_pos unless columns_width[e_idx] >= lf_pos
            row << e
          end
          idx=idx+1
        end
      end
```

end

```
    update_sheet_formatting(sheet1,columns_width)

    xls_stream = StringIO.new('')
    book.write(xls_stream)
    xls_stream.string
  end
```

i get only one issue but i want get all issue single sheet can u help regarding this issue it is need full very urgent
