### ISSUE TITLE
Redmine 2.5.0 で Internal Error

### ISSUE THREAD

**Issue by tcmaru** [two-pack/redmine_xls_export#49]
こんにちは。
redmine_xls_export 0.2.1.t5 を Redmine 2.5.0で使用したところ、Internal Errorが発生しまして、当たりを付けたいと思いましてアドバイス頂けると幸いです。

Environment:
  Redmine version                2.5.0.stable
  Ruby version                   2.0.0-p353 (2013-11-22) [x86_64-linux]
  Rails version                  3.2.17
  Environment                    production
  Database adapter               Mysql2

logは次のようになっています。

Started GET "/redmine/projects/kadai_kanri/issues_xls_export_current" for 192.168.39.56 at 2014-03-12 10:52:51 +0900
Processing by XlsExportController#export_current as HTML
  Parameters: {"project_id"=>"hogehoge"}
  Current user: tcmaru (id=1)
Completed 500 Internal Server Error in 479.0ms

NoMethodError (undefined method `simple_format' for #<XlsExportController:0x007f7eb4e1a2a0>):
  lib/redmine/field_format.rb:301:in`formatted_value'
  lib/redmine/field_format.rb:146:in `formatted_custom_value'
  app/helpers/application_helper.rb:187:in`format_object'
  app/helpers/custom_fields_helper.rb:107:in `show_value'

他のプラグインが影響しているのか、Redmine 2.5.0でカラム名が変更されたのか、どこまで絞っていけば良いかご教示いただけると幸いです。

**Comment by two-pack** [comment]
#46 と同様の原因と思われます。Redmine 2.5.0でshow_valueの実装に変更があったことが原因です。
再現ができていないため、 #46 で修正を行った修正で問題が回避できているか確認していただけるでしょうか？

I think this issue is duplicated #46.
Could you check to fix it with commit of #46 because I don't re-procedure it yet.

**Comment by naitoh** [comment]
自分も Redmine 2.5.1 & Ruby 2.0.0 で同様の現象が発生しました。
master に #46 の　"def show_value_for_xls(value)" メソッドを追加して確認したところ現象が発生しなくなりました。ありがとうございます。

**Comment by two-pack** [comment]
@naitoh さん、問題回避の確認と報告有り難うございます。報告を持ってクローズとします。

@naitoh, Thank you for commenting to fix it.
