### ISSUE TITLE
Error 404 while clicking configuring/details export

### ISSUE THREAD

**Issue by lajish** [two-pack/redmine_xls_export#51]
Hi there,
I just installed this plugin in Bitnami Redmine 2.5.1. Its Quick export works fine but Detailed export & Configuration links redirects to Error 404 page.

**Comment by two-pack** [comment]
Did you install Plugin views with revisions plugin and run following rake?

> rake redmine:plugins:process_version_change RAILS_ENV=production

If you did them, please show your error log and OS.

**Comment by lajish** [comment]
Dear Tatsuya Saito,

Thanks for your valuable support. It was my mistake,  plugin views revisions plugin was not installed in my machine. Right now, everything works fine. 

Once again thanks for your early reply.
