### ISSUE TITLE
Exported excel header cell content to be mapped in 'White' font

### ISSUE THREAD

**Issue by lajish** [two-pack/redmine_xls_export#54]
One thing towards which I need to draw your attention is that it would be more presentable if exported excel column header fonts comes in 'White' color. Right now, column headers which has background color much closer 'Black' which diminishes cell content visibility. Please check the attached image. Please check the attached image.
![xls export](https://cloud.githubusercontent.com/assets/6768694/2944133/100a46b6-d9cf-11e3-9c17-af1281a24655.png)

**Comment by two-pack** [comment]
I changed font color of column header. Please check following image matches your opinion.
![font_color_is_white](https://cloud.githubusercontent.com/assets/378981/2944441/31369534-d9d3-11e3-8659-4ed9bb656fff.png)

**Comment by lajish** [comment]
Dear Tatsuya Saito,

Thank you very much for your early response.

> On May 12, 2014 at 6:16 PM Tatsuya Saito notifications@github.com wrote:
> 
>  I changed font color of column header. Please check following image matches
> your opinion.
>  [font_color_is_white]
> https://cloud.githubusercontent.com/assets/378981/2944441/31369534-d9d3-11e3-8659-4ed9bb656fff.png
> 
>  —
>  Reply to this email directly or view it on GitHub
> https://github.com/two-pack/redmine_xls_export/issues/54#issuecomment-42827200
> .

Regs,
Lajish Lakshmanan
