### ISSUE TITLE
Exported excel column header row should remain freeze while scrolling down

### ISSUE THREAD

**Issue by lajish** [two-pack/redmine_xls_export#55]
I think there should be a feature so that top row i.e. Column header row remain freeze in exported excel by default. This would facilitate the identification of corresponding columns in better way when exported issues are too much. Please incorporate above mentioned suggestion if possible.

**Comment by two-pack** [comment]
This plugin uses spreadsheet gem to export XLS file.
It is difficult for the plugin to implement the feature because I can't find freezing pane feature in spreadsheet gem.
I think it needs to add the feature to spreadsheet gem.

**Comment by lajish** [comment]
Hi Tatsuya,

I can understand this. Now this feature depends on gem specific feature rather
than plugin. Lets hope for incorporation of this feature in upcoming version of
spreadsheet gem. I just put this thing to bring some enhancement to plugin but
right now it is out of your scope.

Anyway, thanks for your precise and immediate response.

> On May 15, 2014 at 9:51 AM Tatsuya Saito notifications@github.com wrote:
> 
>  This plugin uses spreadsheet gem to export XLS file.
>  It is difficult for the plugin to implement the feature because I can't find
> freezing pane feature in spreadsheet gem.
>  I think it needs to add the feature to spreadsheet gem.
> 
>  —
>  Reply to this email directly or view it on GitHub
> https://github.com/two-pack/redmine_xls_export/issues/55#issuecomment-43167190
> .

Regs,
Lajish Lakshmanan

**Comment by two-pack** [comment]
This repository is archived. See #135.
