### ISSUE TITLE
Attachment file name in exported excel should be hyperlink to same image file in folder

### ISSUE THREAD

**Issue by lajish** [two-pack/redmine_xls_export#56]
I am putting forward a suggestion which i hope will get added to this plugin in future. While exporting issues list to excel with attachments. File name of those exported images are available in a column but it is difficult to find them in folders. My suggestion is to provide a hyperlink in place of attachment file name which can enable only single click action to open in corresponding exported image folder.

**Comment by two-pack** [comment]
To implement it needs to set link of relative path because the plugin don't know where it is expanded.
But I can't find how to set link of relative path with spreadsheet and Excel.

**Comment by lajish** [comment]
Hi Tatsuya,

You are right it is not possible to set relative path since user can download
that zip file to anywhere in his/her local machine.
But I have an idea, is it possible to provide redmine link for attachments in
exported excel ?
Please let me share your thought about this.

> On May 15, 2014 at 10:29 AM Tatsuya Saito notifications@github.com wrote:
> 
>  To implement it needs to set link of relative path because the plugin don't
> know where it is expanded.
>  But I can't find how to set link of relative path with spreadsheet and Excel.
> 
>  —
>  Reply to this email directly or view it on GitHub
> https://github.com/two-pack/redmine_xls_export/issues/56#issuecomment-43168720
> .

Regs,
Lajish Lakshmanan

**Comment by two-pack** [comment]
> But I have an idea, is it possible to provide redmine link for attachments in exported excel ?

Its not possible when issue has multiple attachments because a exported cell of attachment hasn't multiple hyperlink.
I think alternative solution is to create a link of the issue.

For the present, I'll continue to find how to set link of relative path.

**Comment by lajish** [comment]
Hi Tatsuya,

Yes, link of the issue is better alternative path. How about it, if exported
excels' bud id cell masks its corresponding link.

> On May 15, 2014 at 10:59 AM Tatsuya Saito notifications@github.com wrote:
> 
> ```
>  > > 
> ```
> 
> > ```
> >  But I have an idea, is it possible to provide redmine link for
> > ```
> > 
> > attachments in exported excel ?
> > 
> > >  Its not possible when issue has multiple attachments because a exported cell
> > > of attachment hasn't multiple hyperlink.
> > >  I think alternative solution is to create a link of the issue.
> 
>  —
>  Reply to this email directly or view it on GitHub
> https://github.com/two-pack/redmine_xls_export/issues/56#issuecomment-43169921
> .

Regs,
Lajish Lakshmanan

**Comment by two-pack** [comment]
I implemented that id column has hyperlink to the issue on Redmine.
Can you test this feature? I'll close this request after your test.

**Comment by lajish** [comment]
I installed new version of plugin and found something which I need to share with you.
In the first picture, i am showing the my redmine setting page where I have mentioned host name for your ready reference. 
Now in second picture, the hyperlink is showing 'redmine ' twice due to which it redirects to wrong URL.
I am a newbie to redmine and don't know whether it is right or wrong.
Please check these two pictures and reply me if am wrong anywhere.

![redmine_xls-01](https://cloud.githubusercontent.com/assets/6768694/2983331/e97559aa-dc21-11e3-8a40-fc50e373f41d.jpg)
![redmine_xls-02](https://cloud.githubusercontent.com/assets/6768694/2983332/e9c19658-dc21-11e3-9523-40fa8e8fe312.jpg)

**Comment by two-pack** [comment]
> the hyperlink is showing 'redmine ' twice due to which it redirects to wrong URL.

I fix it. Please test again.

**Comment by lajish** [comment]
Hi Tatsuya,
I tested it and it is working fine. Tracker ID link is redirecting to correct URL. Thanx for your effort.

**Comment by lajish** [comment]
You can close this issue :+1:
