### ISSUE TITLE
redmine_tweak and redmine_xls_export do not work together

### ISSUE THREAD

**Issue by martin-at-schorsch** [two-pack/redmine_xls_export#62]
redmine_xls_export does not work when redmine_tweak (0.45 - http://github.com/alexandermeindl/redmine_tweaks) is installed too. 

The problem looks simular to #24, but I do not understand the patch you did back then or the links you provided well enough to provide a solution for this matter.

log message:

``````
Started GET "/settings/plugin/redmine_xls_export" for 172.28.53.64 at 2014-07-01 19:18:57 +0200
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_xls_export"}
  Current user: admin (id=1)
Completed 500 Internal Server Error in 4.4ms

NoMethodError (undefined method 'plugin_redmine_xls_export' for #<Class:0x00000003b6f460>):
  app/controllers/settings_controller.rb:69:in 'plugin'```
``````

**Comment by two-pack** [comment]
This problem is different from #24.

redmine_tweak calls **Setting[:plugin_redmine_tweaks]** in hooks.rb:25 from init.rb:79. The call starts to initialize plugins settings **before completed ALL plugins registration**.
It is not redmine XLS export's problem (I think other plugins may have same problem with redmine_tweak).

By the way, I put away the error after enclosing last block in init.rb like following.

```
Rails.configuration.to_prepare do
if ActiveRecord::Base.connection.table_exists?(:settings)
...
end
end
```

But I don't know redmine_tweak works well with above.
I hope this will help.

**Comment by ChauChicken** [comment]
attempts with this

in init.rb redmine_tweaks

``` ruby
...
if ActiveRecord::Base.connection.table_exists?(:settings)
  # Workaround inability to access Setting.plugin_name['setting'], both directly as well as via overridden
  # module containing the call to Setting.*, before completed plugin registration since we use a call to either:
  # * Setting.plugin_redmine_custom_help_url['custom_help_url'] or (and replaced by)
  # * RedmineCustomHelpUrl::Redmine::Info.help_url,
  # which both can *only* be accessed *after* completed plugin registration (http://www.redmine.org/issues/7104)
  #
  # We now use overridden module RedmineCustomHelpUrl::Redmine::Info instead of directly calling
  # Setting.plugin_redmine_custom_help_url['custom_help_url']
+  Rails.configuration.to_prepare do
    unless RedmineTweaks.settings[:remove_help]
      Redmine::Plugin.find('redmine_tweaks').menu :top_menu, :help, RedmineTweaks::CustomHelpUrl::Redmine::Info.help_url, :html => {:target => '_blank'}, :last => true
    end

    require 'settings_helper'
    SettingsHelper.send :include, RedmineTweaksHelper
+  end
end
```

obviously without the '+' ;)

**Comment by martin-at-schorsch** [comment]
I can conform that this patch is working. As far as I was able to test the plugin, it works just fine, no sideeffects detected.
I will report this patch to the redmine_tweak project!
Thx!
