### ISSUE TITLE
All attachments are coorupted

### ISSUE THREAD

**Issue by duboisst** [two-pack/redmine_xls_export#63]
Hi,

I have just installed your plugin.
When I choose to export attachments, the files are exported in the zip file but they are all 1ko size and are corrupted.
Any idea of what could cause that ?

**Comment by two-pack** [comment]
Did you do _bundle install_ when you installed? See https://github.com/two-pack/redmine_xls_export#installation-and-setup

Can you tell me more information?
- How to re-procedure
- OS
- Redmine version
- Plugin version
- Other plugins you install
- gems list

And can you upload exported zip file?

**Comment by duboisst** [comment]
I'm really sorry. It was a redmine configuration issue on my testing environment.
Everything works as expected.
