### ISSUE TITLE
redmine_xls_export - Details Report link is broken

### ISSUE THREAD

**Issue by indraveni** [two-pack/redmine_xls_export#64]
My Installation has, Redmine : 2.5.1-stable

I have Redmine plugin views revisions plugin installed and spreadsheet installed. But rubyzip is shown as if its not installed, where in by bundle show is listing rubyzip. But I don't think rubyzip is having any dependency with Detailed report.

Problem : On clicking Detailed option next to quick in the issues page, I get Page not found error message.

Observation: In my configure page, there is no content under column options or extra options. Does this create any problem ?? Attached screenshot of my configure page.

My Gemfile under redmine is having the following lines

gem "spreadsheet"
gem "rubyzip"

Attaching screenshots and log files for reference.

production.log is having the following content : 

Started GET "/projects/esdm-group/issues_xls_export" for 10.242.0.39 at 2014-07-16 12:14:36 +0530
Processing by XlsExportController#index as HTML
  Parameters: {"project_id"=>"esdm-group"}
  Current user: admin (id=1)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.2ms)
Completed 404 Not Found in 27.9ms (Views: 19.9ms | ActiveRecord: 0.7ms)

Gem Lists are pasted in pastebin at http://pastebin.com/3zphpHfJ

![xls_configure](https://cloud.githubusercontent.com/assets/8177068/3595582/6e982c50-0cb7-11e4-80e3-306550e7082b.JPG)

**Comment by two-pack** [comment]
What verison do you use the plugin? 0.2.1.t6 or older? You can check it at Administration - Plugins page.
According to the log, I think following rake wasn't run with 0.2.1.t5 or older (maybe app/views folder doesn't exist).

```
rake redmine:plugins:process_version_change RAILS_ENV=production
```

If it's true, you should use 0.2.1.t6 which doesn't need the rake command.

But I don't know why your screenshot is shown with your log. Redmine should show error page when it output the log.
Do you have more information like followings?
- Detail how to install this plugin 
- OS, Browser, etc
- Plugin version
- Other plugins you install

**Comment by two-pack** [comment]
I cannot re-procedure it with
- Redmine 2.5.1 and 2.5.2
- Plugin 0.2.1.t6
- OS X 10.9.3
- Chrome 35.0.1916.153
- No other plugins

**Comment by indraveni** [comment]
Hi,

I am working on 0.2.1 version of the plugin. Now freshly installed
redmine_xls_export - 0.2.1.t6 version.

Now the problem resolved. Thankyou

Regards
Indra Veni

**Comment by two-pack** [comment]
> Attaching screenshots and log files for reference.

The screenshot is re-procedured when plugin folder name is NOT **redmine_xls_export**.
