### ISSUE TITLE
Links Quick and Detailed are not visible

### ISSUE THREAD

**Issue by csikkeld** [two-pack/redmine_xls_export#66]
Hello,

I have a problem. I have installed plugin following instructions, but links Quick and Detailed are not  visible.

Thanx for answer in advance

David Csikkel

---

Environment:
  Redmine version                2.5.1.stable
  Ruby version                   2.0.0-p481 (2014-05-08) [x86_64-linux]
  Rails version                  3.2.17
  Environment                    production
  Database adapter               Mysql2
SCM:
  Filesystem  
Redmine plugins:
  redmine_agile                  1.3.2
  redmine_importer               1.2.2
  redmine_plugin_views_revisions 0.0.1
  redmine_xls_export             0.2.1.t6

**Comment by two-pack** [comment]
I cannot re-procedure this problem. I did on above environment with
- OS X 10.9.4.
- redmine_agile-1_3_2-light.zip

Please check followings if you can:
- Can you show configuration page of redmine_xls_export?
- Can you get a screenshot of your Issues page (of cource, links are invisible)?
- Can you try with only redmine_xls_export?

**Comment by csikkeld** [comment]
OS: CentOS 6.5
- Can you show configuration page of redmine_xls_export?
  Yes, configuration page is accessible.
- Can you get a screenshot of your Issues page (of cource, links are invisible)?
  Screenshot of "View all issues":
  ![image](https://cloud.githubusercontent.com/assets/8257111/3699687/4c4f90da-13d7-11e4-91d5-aeca549332b3.png)
- Can you try with only redmine_xls_export?
  I will try it.

**Comment by csikkeld** [comment]
After uninstallation of Agile plugin the same result :-/

**Comment by two-pack** [comment]
> Screenshot of "View all issues":

Links Quick and Detailed are not visible when issues page has no data to display.
Please check again with some issues.

**Comment by csikkeld** [comment]
OK, this was the root cause :-)
I have assumed that it behaves like standard CSV/PDF export.
Thanx a lot.
