### ISSUE TITLE
Internal error: Redmine 500 error: NoMethodError (undefined method `h'

### ISSUE THREAD

**Issue by NezumiRyu** [two-pack/redmine_xls_export#67]
Hello,

I try to update redmine from 2.3.x to 2.5.2.

After lot of work i have that error:

Started GET "/projects/project/issues_xls_export_current" for 10.0.1.1 at 2014-08-26 18:00:04 +0000
Processing by XlsExportController#export_current as HTML
  Parameters: {"project_id"=>"project"}
  Current user: user (id=1)
Completed 500 Internal Server Error in 323.4ms

NoMethodError (undefined method `h' for #<XlsExportController:0x000000088c97d8>):
  app/helpers/application_helper.rb:197:in`format_object'
  app/helpers/custom_fields_helper.rb:107:in `show_value'

Can U help me?

**Comment by two-pack** [comment]
Your problem is like #46.
What version of plugin do you use?
If you use older version, please use 0.2.1.t6.

**Comment by NezumiRyu** [comment]
Redmine Code Review plugin 0.6.3
Redmine Issue Templates plugin 0.0.9
Redmine plugin views revisions plugin 0.0.1
Issues XLS export 0.2.1

I don't understand what i need to do to fix it.
On redmine version 2.3.x all works. 

edit1:
r 2.3.x XLS export:Quick works
r 2.5.x XLS export:Quick error

When i check "Export selected columns only" works, but i need to fix all.

edit2:
I have gem rubyzip (1.1.6). " Extra options (install rubyzip gem to access them)" are gray. Why?

**Comment by two-pack** [comment]
> I don't understand what i need to do to fix it.

Update the plugin 0.2.1 to 0.2.1.t6.
See https://github.com/two-pack/redmine_xls_export#installation-and-setup

**Comment by NezumiRyu** [comment]
Works. Thx.
