### ISSUE TITLE
Possible conflict with issues controller

### ISSUE THREAD

**Issue by ppoektos** [two-pack/redmine_xls_export#68]
Your plugin somehow causes that one redmine function doesn't work.

http://www.redmine.org/issues/16568

**Comment by two-pack** [comment]
Do you reprocedure this problem after uninstalling redmine xls export?
This plugin effects Issues list page, NOT changeset page.

**Comment by two-pack** [comment]
> This plugin effects Issues list page, NOT changeset page.

This plugin does NOT effect issue page too.
Please check to reproduce this problem after uninstalling redmile xls export.
If reproduce it, reason of this problem isn't this plugin.

**Comment by ppoektos** [comment]
Thanks. Will do this.

On Thu, Sep 25, 2014 at 3:39 AM, Tatsuya Saito notifications@github.com
wrote:

> This plugin effects Issues list page, NOT changeset page.
> 
> This plugin does NOT effect issue page too.
> Please check to reproduce this problem after uninstalling redmile xls
> export.
> If reproduce it, reason of this problem isn't this plugin.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/two-pack/redmine_xls_export/issues/68#issuecomment-56759683
> .

## 

Best / ó ÎÁÉÌÕÞÛÉÍÉ ÐÏÖÅÌÁÎÉÑÍÉ

 _Pavel Potcheptsov_

   LLC EKTOS-Ukraine

System administrator

   1, Academika Proskury

Mobile UA: +38 050 3642391

Home UA: +380 572 931115

   61070 Kharkiv

   www.ektos.com.ua http://www.ektos.net/

E-mail:

ppo@ektos.net

  Skype:      potcheptsov.pavel

**Comment by two-pack** [comment]
This repository is archived. See #135.
