### ISSUE TITLE
Custom fields of type Integer/Float etc. are considered strings

### ISSUE THREAD

**Issue by cmuller** [two-pack/redmine_xls_export#69]
We have custom fields that are of type 'Integer' and before (in 0.2.1.t3) they appeared as such in an XLS export. But now (0.2.1.t6) there is a quote in front of them (in their Excel or Libreoffice cel)l and they cannot appear for example in a `sum(...)` formula. it seems to me that this has changed since the refactor coming with #25 where a big case on `c.custom_field.field_format` has been replaced with a call to `detect`. When I try to set `v` to `Integer(issue.custom_value_for(c.custom_field).to_s)` it works again but I am not confortable enough in Ruby to propose a patch, sorry.
Did I miss something in the use of the plugin?

**Comment by two-pack** [comment]
Thank you for reporting. It's a bug. Please wait to fix.

**Comment by cmuller** [comment]
Thanks a lot! I tested it with Integer-type of custom fields and it works well.
