### ISSUE TITLE
Compatible with redmine 2.1.x?

### ISSUE THREAD

**Issue by cforce** [two-pack/redmine_xls_export#7]

**Comment by two-pack** [comment]
'master' branch is not compatible with redmine 2.x.
But I imported latest redmine_xls_export plugin from official(*) to 'official' and 'features' branches.
And I checked them to run on redmine 2.1.4.

By the way, 'master' branch has some features which is not included official plugin.
I'm going to apply them to 'features' branch with #8 .

**Comment by cforce** [comment]
Please expalin in overview site that you inherit from original and what features are added. tx!
