### ISSUE TITLE
Conflict with redmine_category_tree plugin

### ISSUE THREAD

**Issue by angruche** [two-pack/redmine_xls_export#70]
After install redmine_category_tree plugin, add a few categories to issues, redmine_xls_export fails:

NoMethodError (undefined method `h' for #<XLS_JournalQueryColumn:0x3a7c17a2>):
  app/helpers/issues_helper.rb:307:in`show_detail'

Environment info:

Environment:
  Redmine version                2.5.2.stable
  Ruby version                   1.9.3-p392 (2014-09-03) [java]
  Rails version                  3.2.19
  Environment                    production
  Database adapter               MySQL
SCM:
  Filesystem  
Redmine plugins:
  collapsed_journals             0.0.2
  redmine_category_tree          0.0.5
  redmine_issue_templates        0.0.9
  redmine_xls_export             0.2.1.t6
  redmine_zenedit                0.0.2

**Comment by two-pack** [comment]
redmine_category_tree plugin conflicts redmine_xls_export.
I added new code to handle issue category for redmine_category_tree.
In XLS file, issue categories are separated by ">", like "parent > child".

**Comment by two-pack** [comment]
I tested with redmine_category_tree version 0.0.5.

**Comment by angruche** [comment]
Tested and ok, thanks!!!
