### ISSUE TITLE
export attachments broken and 2 repeated issue id columns in the exported xls

### ISSUE THREAD

**Issue by fengyedou** [two-pack/redmine_xls_export#71]
Installation steps:

1.I installed rubyzip gem, and there is such line In the \BitNami\redmine-2.3.2-0\apps\redmine\htdocs\gemfile.lock after installing that gem
     rubyzip (1.1.6)
     rubyzip (>= 1.0.0)

2.migrate as redmine plug-in common steps.

Question:

I have seen this note, I am not sure of that meaning, that means I need to remove rubyzip line FORM gemfiile.lock I listed above? I donot use bundle install, I just installed rubyzip.gem manually then migrate the database. Can i omit this note?

NOTE: Remove specified version for ‘rubyzip’ and ‘zip-zip’ in Gemfile if you use Redmine 2.3.x or older before ‘bundle install’.

Issue:

1.if installed rubyzip gem, export attachments can be selected, and click quick export, there will be a zip file to export, but open the zip file, the file in it called workbook cannot be opened, it is broken.
2.exported xls file has 2 repeated info. in the 1st, 2nd column, they are both issue ID.

Can the 2 be resolved?

**Comment by two-pack** [comment]
This plugin requires zip-zip gem if you use ruby-zip >= 1.0.0.
I do not know your installation is success or not. I tested with bundler only. Can you try use bundler for install?
Note that you need --no-deployment option with bundle install if you use BitNami Redmine.

**Comment by two-pack** [comment]
> NOTE: Remove specified version for ‘rubyzip’ and ‘zip-zip’ in Gemfile if you use Redmine 2.3.x or older before ‘bundle install’.

See #43.

**Comment by two-pack** [comment]
> 1.if installed rubyzip gem, export attachments can be selected, and click quick export, there will be a zip file to export, but open the zip file, the file in it called workbook cannot be opened, it is broken.

Maybe it's caused missing zip-zip. In my environment, OS X 10.9.5, only rubyzip without zip-zip and Redmine 2.3.2, I have a zip file but unzipped file is invalid file.

> 2.exported xls file has 2 repeated info. in the 1st, 2nd column, they are both issue ID.

Is this same way to reproduce? extracted xls file?
Or did NOT you set to export attachments?

**Comment by two-pack** [comment]
What version of this plugin do you use? 0.2.1.t6?

**Comment by fengyedou** [comment]
HI,

i DOWNLOAD FORM GITCLUGB,the latest version:0.2.1.t6.
I removed the plug-in and re set up again like below, My installation step is:

1)bundle install -
2)although bundle install is performed, rubyzip1.1.6 and zip-zip 0.3 are not installed automatically, so I download them from rubygems.org and installed the 2 gems.
3)migrate the plug-in

Then in the gemfile.lock there are 2 lines:
    Line 175:     rubyzip (1.1.6)
    Line 243:   rubyzip (>= 1.0.0)

I set the configuration of redmine, make exported attachment be selected in the plug-in configuration.

And use xls report-quick, the zip files are exported, and open the zip folder "workbook" is in it, but I cannot open it directly, if I use excel to open this file, excel will close, cannot open that file.

What is the format of extracted  "Workbook"? it does not have any info. It is not a xls file.
I will attach the images I have setup and configured for you to check. please have a look at http://www.redmine.org/boards/3/topics/11986?r=44359#message-44359

If I want to export xls file, I need to unselect "export attachments" in the plug-in configuration, and exported xls file has 2 repeate issue id in the 1st and 2nd columuns, I can attach the files in redmine
And the other issue of exported xls has 2 repeated xls columns with issue id, I also attatch the exported xls file here:http://www.redmine.org/boards/3/topics/11986?r=44359#message-44359

If extra export option(export attachments) are selected, only zip files can be exported, but now extracted zip file can not be opened by excel, that is the 2 issues I summarized.

Thanks.

**Comment by fengyedou** [comment]
By the way,  I checked gemfile.lock, spreadsheet (0.9.7) is in that file, too.

**Comment by two-pack** [comment]
Please try to run bundler in Redmine root folder, not plugins folder.
Have any changes?

**Comment by two-pack** [comment]
Using BitNami Redmine 2.3.2-3 on Windows (Clean install), I tried to run bundle install like following.
I succeeded bundler. And after restarting Redmine, exported files (zip and xls) have no problem.

```
C:\Bitnami\redmine-2.3.1-3\apps\redmine\htdocs>bundle install --no-deployment
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Using rake (0.9.2.2)
....
Installing ruby-ole (1.2.11.7)
Installing rubyzip (1.1.6)
Installing spreadsheet (1.0.0)
Using thin (1.3.1)
Installing zip-zip (0.3)
Your bundle is complete!
```

I cannot reproduce it, so I need more information for researching...
What do you install other plugins? Can you try clean environment like above?

**Comment by two-pack** [comment]
Version 0.2.1.t3 had id duplicated issue #26. But already fixed it.

**Comment by two-pack** [comment]
> I also attatch the exported xls file here:http://www.redmine.org/boards/3/topics/11986?r=44359#message-44359

Attached images here. Only images, no exported xls file?
![config-export-extract](https://cloud.githubusercontent.com/assets/378981/4701069/a0037b58-5854-11e4-83cf-acb0729fd7d5.png)
![repeated issue id for exported xls](https://cloud.githubusercontent.com/assets/378981/4701070/a00e7bd4-5854-11e4-97fd-c4c72cc4f472.png)
![setup](https://cloud.githubusercontent.com/assets/378981/4701071/a0409470-5854-11e4-95b2-bcc19659cc2c.jpg)

**Comment by fengyedou** [comment]
Sorry, our company xls file cannot be opened outside, so I donot send the file just gave a snapshot of the xls. The 1st column is issue id, the 2nd column is still issue ID, it is exported xls file, the configuration you can see above pictures.

**Comment by fengyedou** [comment]
Hi, it is good news that I have succeed!!! I downloaded the lateste version and run bundle install as you guide, then all the issues including repeated columns are fixed!!!

Can I ask more about some features?

1.there is Date format options in the plug-in configuration, if I change all the date format to yyyy.mm.dd, then the default redmine date format "09/15/2014 02:36 pm" will be changed to 2014.09.15 in the exported xls file, right?

I think it is very great feature for statistics.

2."Export journal entries "-----if it is chosen, the exported issue report will have one column "Journal",right?

3.Journals are generated by each issue,or other rule?I checked the issue report, the issue number is not the journal number, but open one journal, it is only for one issue history.

4."Split by grouping criteria "--I select this option, but from the exported xls file, I donot see what difference if I select it or not, what is it for, can you take an example?

5.Export relations --I select this option, the same question above, not see any difference selected or not, what is it for?

Thanks again for your patience help!!

**Comment by fengyedou** [comment]
Can I submit a requirement?

1.I found the xls report detailed option has not have "export description", I download another older version, there is such feature, can you add it to the latest release? It is really important info. for an issue, now I cannot export description in the issue list.

2.I have checked created date format, if I set in the date format option with "yyyy.mm.dd", the exported created date still show"2014/10/20  5:16:16", can you optimize that? if format is "yyyy.mm.dd",then show "2014.10.20"or "2014/10/20",if format is "yyyy.mm.dd hh:mm:ss", the exported date show "2014/10/20 5:16:16".

That is the 2 features I think it is good to add.

Thanks and wait for your reply.

**Comment by fengyedou** [comment]
By the way, I check the plug-in version I installed, it is 0.2.1.t6, I download this release from https://github.com/two-pack/redmine_xls_export/releases

//////here are the configuraton items in the plug-in, there is not a "export descriptions" option, but if I download from here "https://github.com/two-pack/redmine_xls_export" directly(at the right side, there is a "Download ZIP "), it has such option "export descriptions",but this zip release has issues that exported files having repeated issue id columns, so I am confused if the release files has some problems, can you check with that?////////
Settings: Issues XLS export

Columns options: Export relations Export watchers Export journal entries List attachments
Export options :Export selected columns only Split by grouping criteria Suggest export name
Extra options:Export attachments Issues journals as separate files Export status histories

**Comment by two-pack** [comment]
> I have succeed!

Sound good :)

Many questions you wrote are off topic of this issue.
So please issue new one and each one if you think they are problems. If not, please use forum.
After I will answer them.

**Comment by two-pack** [comment]
> I have succeed!

Sound good :)

Many questions you wrote are off topic of this issue.
So please issue new one and each one if you think they are problems. If not, please use forum.
After I will answer them.

**Comment by fengyedou** [comment]
OK, i WILL SUBMIT a new issue and a new feature ruquest.
