### ISSUE TITLE
export descriptions option again

### ISSUE THREAD

**Issue by fengyedou** [two-pack/redmine_xls_export#72]
I check the plug-in version I installed, it is 0.2.1.t6, I download this release from https://github.com/two-pack/redmine_xls_export/releases

//////here are the configuraton items in the plug-in, there is not a "export descriptions" option, but if I download from here "https://github.com/two-pack/redmine_xls_export" directly(at the right side, there is a "Download ZIP "), it has such option "export descriptions",but this zip release has issues that exported files having repeated issue id columns, so I am confused if the release files has some problems, can you check with that?////////

 Settings: Issues XLS export

Columns options: Export relations Export watchers Export journal entries List attachments
 Export options :Export selected columns only Split by grouping criteria Suggest export name
 Extra options:Export attachments Issues journals as separate files Export status histories

**Comment by two-pack** [comment]
That option is deprecated.
You can select description column on Redmine issues page option. If you select it, the plugin exports with description.
See #26.

**Comment by fengyedou** [comment]
Sorry, I post wrong place.

Hi,

I know redmine has description option for issue list, but that needs to select each time when you want to export issues, the description option canot be fixed, if developer forgets to select from redmine option, it needs to export again.

But if the plug-in has the exported description option, it can be fixed during plug-in configuration. 
Is there any way to handle this request? I hope the description option can be fixed during some configuration, no need to select each time when exported.

Thanks.

**Comment by two-pack** [comment]
It's by design.
I need many time to implement your request, but not enough time.

**Comment by fengyedou** [comment]
And I found redmine default exported csv will put "description" at the last column, if the description is checked, but exported xls will put "description" at the 2nd column, can it be an option for the description postion? We have so many statistics work, so we define the issue list template to do that, and put the description at the last column as default redmine format, if we use xls export, we need to change the templates for the description position is changed, Is it possible to put a option for description position in the plug-in?

**Comment by fengyedou** [comment]
I see, if there is not so much time to implement a fix description export in the plug-in, we can custom query in redmine and make the query fixing description and guide developers to use query to export, not directly using issue list, it is a way to resolve, though a bit hard to change developer's habbits.

**Comment by two-pack** [comment]
This repository is archived. See #135.
