### ISSUE TITLE
Feature description questions

### ISSUE THREAD

**Issue by fengyedou** [two-pack/redmine_xls_export#73]
Can I ask more about some features?

1.there is Date format options in the plug-in configuration, if I change all the date format to yyyy.mm.dd, then the default redmine date format "09/15/2014 02:36 pm" will be changed to 2014.09.15 in the exported xls file?

I think it is very great feature for statistics.

2."Export journal entries "-----if it is chosen, the exported issue report will have one column "Journal",right?

3.Journals are generated by each issue,or other rule?I checked the issue report, the issue number is not the journal number, but open one journal, it is only for one issue history.

4."Split by grouping criteria "--I select this option, but from the exported xls file, I donot see what difference if I select it or not, what is it for, can you take an example?

5.Export relations --I select this option, the same question above, not see any difference selected or not, what is it for?

Thanks again for your patience help!!

**Comment by fengyedou** [comment]
I think if release notes has more examples for describing the features, it will help much to understand how to use the new features.

**Comment by two-pack** [comment]
1. and 2. are yes.

> 3.Journals are generated by each issue,or other rule?

If issue number is 1, journal file name is `00001_journal_details.xls`.

> 4."Split by grouping criteria "

If you use **Group result by** on Issues page, exported xls has multiple sheets by group.

> 5.Export relations

I don't know meaning of this option :(
I'm not original author of this plugin (see readme), so I don't understand some functions.
Maybe no difference now, I check Redmine 2.4.6.

**Comment by two-pack** [comment]
> 5.Export relations

I think this option switches visible of **Related issues** column.
I issue this problem #77.

**Comment by two-pack** [comment]
I answer all questions.
