### ISSUE TITLE
A required new feature about date format

### ISSUE THREAD

**Issue by fengyedou** [two-pack/redmine_xls_export#74]
I have checked created date format, if I set in the date format option with "yyyy.mm.dd", the exported created date still show"2014/10/20 5:16:16", can you optimize that? if format is "yyyy.mm.dd",then show "2014/10/20",if format is "yyyy.mm.dd hh:mm:ss", the exported date show "2014/10/20 5:16:16".

That is the feature I think will be good for issue data analysis when the date format can be handled after exported, I think it is good to add.

Thanks and wait for your reply.

**Comment by two-pack** [comment]
Please more information to reproduce it.
OS
Redmine version
Plugin version
App to open xls and version
Other plugins you install

**Comment by fengyedou** [comment]
I uses bitnami-redmine 2.3.2, we installed the redmine under windows 2008 server.

Now the exported xls file shows date as "2014/10/20 5:16:16", if it can be chosen to show "2014/10/20" and also be chosen to shown "2014/10/20 5:16:16", it will be better for analysis.

Now my method is to handle the date with excel formula after exported the file. It is not direct way.

My env. info is below:

Environment:
  Redmine version                2.3.2.stable
  Ruby version                   1.9.3-p231 (2012-05-25) [i386-mingw32]
  Rails version                  3.2.13
  Environment                    production
  Database adapter               Mysql2
Redmine plugins:
  clipboard_image_paste          1.8
  fields_permissions             1.0.0
  progressive_projects_list      1.0.0
  redmine_agile                  1.3.3
  redmine_app__space             1.0.3
  redmine_banner                 0.0.9
  redmine_better_gantt_chart     0.9.0
  redmine_code_review            0.6.3
  redmine_dashboard              2.3.3
  redmine_documents_short        0.3.0
  redmine_issue_checklist        2.0.5
  redmine_issue_templates        0.0.8
  redmine_knowledgebase          3.0.4
  redmine_logs                   0.0.5
  redmine_monitoring_controlling 0.1.1
  redmine_plugin_views_revisions 0.0.1
  redmine_release_notes          1.3.1
  redmine_reminder               0.3.1
  redmine_theme_changer          0.1.0
  redmine_touch                  0.0.2
  redmine_xls_export             0.2.1.t6
  redmine_xlsx_format_issue_exporter 0.1.0
  scrum                          0.7.0
  sidebar_hide                   0.0.6
  wiking                         1.0.0b

**Comment by two-pack** [comment]
I try to reproduce it in bitnami-redmine 2.3.2, but I cannot reproduce it.

**Comment by fengyedou** [comment]
Hi, have you try to export a xls file and check the date?

1.I config the plug-in with Date format options

Created: yyyy.mm.dd
Updated: yyyy.mm.dd
Start date: yyyy.mm.dd
Due date: yyyy.mm.dd

2.Go to issue page, and issue list shows data format like:
 Created: 09/30/2014 02:33 pm
 Closed: 09/30/2014 02:38 pm
 Start Date: 09/30/2014
 Due Date: 10/01/2014
 Updated: 09/30/2014 02:38 pm

They are redmine default date format.

3.Export xls file,then date format is like below:

Created: 2014/9/30  6:33:19
Closed: 2014/9/30  6:38:39
Start Date: 2014/9/30
Due Date: 2014/10/1
Updated: 2014/9/30  6:38:39

the real format needs to click the cell to see, for I have tested using excel formula, e.g.

if(xx=2014.09.30, y,n), the result is n. and I change the formula to if(xx="2014/9/30 6:33:19",y,n), then the result is y.

I will paste the snapshot in redmine forum.

You can check it here. http://www.redmine.org/boards/3/topics/11986?r=44428

//////The feature request is if date format is set to yyyy.mm.dd or yyyy/mm/dd, the cell contents shows real yyyy.mm.dd or yyyy/mm/dd, no hh:mm:ss info. within it.

4.and another issue I found is the time shows maybe the US timezone, e.g in our timezone, the created date is 09/30/2014 02:33 pm, but the exported xls shows 2014/9/30  6:33:19, seems 8 hours earlier, I think there need a timezone option in the plug-in configuration, I have set the timezone in my account with Beijing Time, but exported xls still shows other timezone time. I will submit this as a new issue.

**Comment by two-pack** [comment]
By design. This plugin set cell format, not change values.

**Comment by fengyedou** [comment]
So  it is not designed to change value, right? I see... then I need to handle with the value with excel formula.

**Comment by two-pack** [comment]
I implemented only to set cell format.
I think this plugin shoud NOT change raw values from Redmine.
So I do not think to implement you request, and issue was closed.

**Comment by fengyedou** [comment]
OK, I understand:) Thanks.
