### ISSUE TITLE
Exported xls's date contens doesn't show local timezone

### ISSUE THREAD

**Issue by fengyedou** [two-pack/redmine_xls_export#75]
I found is the time shows maybe the US timezone or other country's timezone, e.g in our timezone, the created date is 09/30/2014 02:33 pm, but the exported xls shows 2014/9/30 6:33:19, seems 8 hours earlier, I think there need a timezone option in the plug-in configuration, I have set the timezone in my account with Beijing Time, but exported xls still shows other timezone time. 

The timezone of our local place is  (GMT+08:00) Beijing.

It can be a new feature, or maybe there is solution I donot know, please tell me if there is already solution to solve the timezone.

**Comment by two-pack** [comment]
> exported xls still shows other timezone time.

I reproduced it. I think using local timezone is better.
But need much time.

**Comment by fengyedou** [comment]
I think there are 2 ways, 1 is to give a option to select timezone in plug-in configuration, then different country's guys can choose to export issue with the right date of their own timezone, the other is automatically utilizing the timezone the user account sets, I donot know t he difficulty, maybe needs much time, but I do belive it is a mandatory feature, if using by guys around the world, appreciate your work!!
