### ISSUE TITLE
A new feature---add "Closed" to date foramt options

### ISSUE THREAD

**Issue by fengyedou** [two-pack/redmine_xls_export#76]
Can you add "Closed" to "Date format options ", now there is start date, due date, updated, created, but lack of "Closed", I think it is key info. for to know the real closed date for an issue.

**Comment by fengyedou** [comment]
Sorry, I donot know if you have see another plug-in issue I submitted, you can check it here.
http://www.redmine.org/boards/3/topics/29545

I download the plug-in using download zip from "https://github.com/logical-and/redmine_smart_issues_sort"

**Comment by two-pack** [comment]
Why do you indicate that plugin?

**Comment by fengyedou** [comment]
Is that redmine_smart_issues_sort" reated by you? maybe I make a mistake...

**Comment by fengyedou** [comment]
Can you have that Closed to be added in the date format option?

**Comment by two-pack** [comment]
> Can you add "Closed" to "Date format options "

Maybe yes. I'm going to implement it when I have enough time.

**Comment by fengyedou** [comment]
Ok, I will keep on following your implementation:)
