### ISSUE TITLE
Export relations option does not work.

### ISSUE THREAD

**Issue by two-pack** [two-pack/redmine_xls_export#77]
Export relations option does not work.
This option should switch visibility of **Related issues** column.

**Comment by fengyedou** [comment]
Yes, thanks, I have catched all the explaination for the options, hope to get the fix of related issues.

**Comment by fengyedou** [comment]
How this works? I updated the plug-in and export with relations selected, and confirm there is issue having related issues, but from the exported xls file, no relation issues column displayed.

Can you take an example?

**Comment by two-pack** [comment]
> export with relations selected

You have to select relations on issues page or uncheck **Export selected columns only**.
And **Export relations** option is unchecked, relations column is not exported.

**Comment by two-pack** [comment]
Export relations is not useful because you can switch exporting or not using issues pages option.
I think that option will be removed. That reason is like #72.

**Comment by fengyedou** [comment]
thanks:)　Ｉ　ｓｅｅ
