### ISSUE TITLE
Bug with Redmine 2.5.2

### ISSUE THREAD

**Issue by yquenechdu** [two-pack/redmine_xls_export#80]
Hi,

I installed a Redmine 2.5.2 clean version. After install plugin redmine_xls_export, I obtain this message  : 

/home/opt/redmine/app/models/setting.rb:138: syntax error, unexpected '-', expecting ';' or '\n'
    def self.plugin_redmine_xls_export-features
                                       ^
/home/opt/redmine/app/models/setting.rb:140: syntax error, unexpected keyword_end, expecting $end (SyntaxError)
  /home/opt/redmine/app/models/setting.rb:138:in `class_eval'
  /home/opt/redmine/app/models/setting.rb:138:in`block in class:Setting'
  /home/opt/redmine/app/models/setting.rb:124:in `each'
  /home/opt/redmine/app/models/setting.rb:124:in`class:Setting'
  /home/opt/redmine/app/models/setting.rb:18:in `<top (required)>'
  /usr/local/rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:251:in`require'
  /usr/local/rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:251:in `block in require'
  /usr/local/rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:236:in`load_dependency'
  /usr/local/rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:251:in `require'
  /usr/local/rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:359:in`require_or_load'
  /usr/local/rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:313:in `depend_on'
  /usr/local/rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:225:in`require_dependency'
  /usr/local/rvm/gems/ruby-1.9.3-p327/gems/railties-3.2.19/lib/rails/engine.rb:444:in `block (2 levels) in eager_load!'
  /usr/local/rvm/gems/ruby-1.9.3-p327/gems/railties-3.2.19/lib/rails/engine.rb:443:in`each'
  /usr/local/rvm/gems/ruby-1.9.3-p327/gems/railties-3.2.19/lib/rails/engine.rb:443:in `block in eager_load!'
  /usr/local/rvm/gems/ruby-1.9.3-p327/gems/railties-3.2.19/lib/rails/engine.rb:441:in`each'
  /usr/local/rvm/gems/ruby-1.9.3-p327/gems/railties-3.2.19/lib/rails/engine.rb:441:in `eager_load!'
  /usr/local/rvm/gems/ruby-1.9.3-p327/gems/railties-3.2.19/lib/rails/application/finisher.rb:53:in`block in module:Finisher'
  /usr/local/rvm/gems/ruby-1.9.3-p327/gems/railties-3.2.19/lib/rails/initializable.rb:30:in `instance_exec'
  /usr/local/rvm/gems/ruby-1.9.3-p327/gems/railties-3.2.19/lib/rails/initializable.rb:30:in`run'
  /usr/local/rvm/gems/ruby-1.9.3-p327/gems/railties-3.2.19/lib/rails/initializable.rb:55:in `block in run_initializers'
  /usr/local/rvm/gems/ruby-1.9.3-p327/gems/railties-3.2.19/lib/rails/initializable.rb:54:in`each'
  /usr/local/rvm/gems/ruby-1.9.3-p327/gems/railties-3.2.19/lib/rails/initializable.rb:54:in `run_initializers'
  /usr/local/rvm/gems/ruby-1.9.3-p327/gems/railties-3.2.19/lib/rails/application.rb:136:in`initialize!'
  /usr/local/rvm/gems/ruby-1.9.3-p327/gems/railties-3.2.19/lib/rails/railtie/configurable.rb:30:in `method_missing'
  /home/opt/redmine/config/environment.rb:14:in`<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in`block in <main>'
  /usr/local/rvm/gems/ruby-1.9.3-p327/gems/rack-1.4.5/lib/rack/builder.rb:51:in `instance_eval'
  /usr/local/rvm/gems/ruby-1.9.3-p327/gems/rack-1.4.5/lib/rack/builder.rb:51:in`initialize'
  config.ru:1:in `new'
  config.ru:1:in`<main>'
  /usr/local/rvm/gems/ruby-1.9.3-p327/gems/passenger-4.0.50/helper-scripts/rack-preloader.rb:112:in `eval'
  /usr/local/rvm/gems/ruby-1.9.3-p327/gems/passenger-4.0.50/helper-scripts/rack-preloader.rb:112:in`preload_app'
  /usr/local/rvm/gems/ruby-1.9.3-p327/gems/passenger-4.0.50/helper-scripts/rack-preloader.rb:158:in `<module:App>'
  /usr/local/rvm/gems/ruby-1.9.3-p327/gems/passenger-4.0.50/helper-scripts/rack-preloader.rb:29:in`module:PhusionPassenger'
  /usr/local/rvm/gems/ruby-1.9.3-p327/gems/passenger-4.0.50/helper-scripts/rack-preloader.rb:28:in `<main>' 

Regards
Yannick

**Comment by two-pack** [comment]
Where did you install this plugin?
You MUST install to plugins/redmine_xls_export .

**Comment by yquenechdu** [comment]
When I install the download package, I obtain this error message. But with a git clone, I have no problem.
Excuse me, for the disturb

Regards
Yannick
