### ISSUE TITLE
html tags in exported xls (desciption, journals..) when using ckeditor plugin

### ISSUE THREAD

**Issue by popy2k14** [two-pack/redmine_xls_export#85]
I am using ckeditor as default text editor in redmine.
After export an xls of issues the description, journals includes all html tags.
I have fixed this issue on my local version based on t7.

Here is the fixed file:
http://www37.zippyshare.com/v/qqtFH2lT/file.html

Keep up the good work!
Please include it in upcomming releases.

thx

**Comment by two-pack** [comment]
@popy2k14 , Thank you for contributing :)
Please tell us more details to fix, purpose, how to, and more.

> I am using ckeditor as default text editor in redmine.
> If we don't use chkeditor, do NOT have any problem?

BTW Cloud you use pull-request?

**Comment by popy2k14** [comment]
Yes when you dont use ckeditor the issue shouldnt come up because the text has no html tags :)
Here is a unified diff patch: http://www32.zippyshare.com/v/YwebS99Y/file.html

**Comment by two-pack** [comment]
- Are html tags included ONLY in description and journals?
- Please tell me input description html and expected output text for test.
- What version of nokogiri do you use? latest?

**Comment by popy2k14** [comment]
- Are html tags included ONLY in description and journals?
  -> yes, so it was in my case. With my fixed version i cant find any html tags elsewhere in the exported xls.
- Please tell me input description html and expected output text for test.
  -> just use ckeditor as default text plugin and create a ticket where you use lists, enter and so on. When you export this with your latest t7 version the description shows tags as <ul> or <p> and so on. After using my patched version all this tags gets stripped out of description and journals.
- What version of nokogiri do you use? latest?
  -> nokogiri (1.6.5, 1.6.3.1)

**Comment by two-pack** [comment]
> just use ckeditor as default text plugin
> Do you use redmine_ckeditor?
> https://github.com/a-ono/redmine_ckeditor

**Comment by popy2k14** [comment]
Yep, this plugin in version 1.0.16.

**Comment by two-pack** [comment]
I merge your patch and add option to strip HTML tags or not.

**Comment by popy2k14** [comment]
thx, pOpY
