### ISSUE TITLE
Spent time report feature

### ISSUE THREAD

**Issue by fengyedou** [two-pack/redmine_xls_export#89]
Can it support export spent time report? Now spent time report only has csv default export format.

**Comment by two-pack** [comment]
You can export Spent time with this plugin.
Please select spent time column on Issues page or export all columns.

**Comment by fengyedou** [comment]
@two-pack, I know all columns from issue page can be exported, what I mean is not here, you can check "Overview" in one redmine project, at the right side of this page there is "Spent Time" Menu,"Report" is below this menu, if I click into it to get spent time report, this report can only be exported as csv, not xls,xlsx.

So I request if this feature can be added, not only issue page can use xls export, but also spent time report page can use it.

**Comment by two-pack** [comment]
I understand your request.
But I think not to implement new feature now.

**Comment by rakshazi** [comment]
Need it too :(

**Comment by two-pack** [comment]
I implemented to export spent time on redmine_xlsx_format_issue_exporter.
Please use it :)
https://github.com/two-pack/redmine_xlsx_format_issue_exporter/issues/37

**Comment by two-pack** [comment]
This repository is archived. See #135.
