### ISSUE TITLE
404 Error on Bitnami Redmine 3.0.3

### ISSUE THREAD

**Issue by mags1225** [two-pack/redmine_xls_export#91]
I currently have the following installed in the plugins folder:
redmine_plugin_views_revisions
redmine_xls_export

Ran bundle install, and rake redmine:plugins:process_version_change RAILS_ENV=production

Plugin shows installed in Redmine, but when I click on the export button or export detailed, I get a 404 error.

Production.log shows the following error:
ActionController::RoutingError (No route matches [GET] "/redmine/projects/tester-123abc123-12/issues_xls_export_current"):

May just not be installed properly, but I have tried a few different methods of installing.

**Comment by two-pack** [comment]
Please check how to install again. You do NOT need redmine_plugin_views_revisions because you use Redmine 3.0.3.
https://github.com/two-pack/redmine_xls_export#installation-and-setup

If you'll have error yet, please write more information, like OS, installed folders and files, how to install and so.

**Comment by mags1225** [comment]
I removed **redmine_plugin_views_revisions** and also **redmine_xls_export** to completely reinstall plugin.

OS is Server 2012 R2
Copied folder **redmine_xls_export** to **C:\Bitnami\redmine-3.0.3-0\apps\redmine\htdocs\plugins\** folder

Ran the following from **C:\Bitnami\redmine-3.0.3-0\apps\redmine\htdocs\** folder: (As instructed by bitnami plugin installation guide)

```
bundle install --without development test postgresql sqlite --no-deployment
bundle install --without development test postgresql sqlite --deployment
ruby bin/rake redmine:plugins RAILS_ENV=production
```

Below is the full error from production.log:

```
Started GET "/redmine/redmine/projects/tester-123abc123-12/issues_xls_export_current" for 127.0.0.1 at 2015-06-22 09:55:22 -0700

ActionController::RoutingError (No route matches [GET] "/redmine/projects/tester-123abc123-12/issues_xls_export_current"):
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/ruby/2.0.0/gems/railties-4.2.1/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/bundle/ruby/2.0.0/gems/railties-4.2.1/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/bundle/ruby/2.0.0/gems/railties-4.2.1/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.6.0/lib/rack/methodoverride.rb:22:in `call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.6.0/lib/rack/runtime.rb:18:in `call'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/static.rb:113:in `call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.6.0/lib/rack/sendfile.rb:113:in `call'
  vendor/bundle/ruby/2.0.0/gems/railties-4.2.1/lib/rails/engine.rb:518:in `call'
  vendor/bundle/ruby/2.0.0/gems/railties-4.2.1/lib/rails/application.rb:164:in `call'
  vendor/bundle/ruby/2.0.0/gems/railties-4.2.1/lib/rails/railtie.rb:194:in `public_send'
  vendor/bundle/ruby/2.0.0/gems/railties-4.2.1/lib/rails/railtie.rb:194:in `method_missing'
  vendor/bundle/ruby/2.0.0/gems/rack-1.6.0/lib/rack/urlmap.rb:66:in `block in call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.6.0/lib/rack/urlmap.rb:50:in `each'
  vendor/bundle/ruby/2.0.0/gems/rack-1.6.0/lib/rack/urlmap.rb:50:in `call'
  vendor/bundle/ruby/2.0.0/gems/thin-1.6.1-x86-mingw32/lib/thin/connection.rb:82:in `block in pre_process'
  vendor/bundle/ruby/2.0.0/gems/thin-1.6.1-x86-mingw32/lib/thin/connection.rb:80:in `catch'
  vendor/bundle/ruby/2.0.0/gems/thin-1.6.1-x86-mingw32/lib/thin/connection.rb:80:in `pre_process'
  vendor/bundle/ruby/2.0.0/gems/thin-1.6.1-x86-mingw32/lib/thin/connection.rb:55:in `process'
  vendor/bundle/ruby/2.0.0/gems/thin-1.6.1-x86-mingw32/lib/thin/connection.rb:41:in `receive_data'
  vendor/bundle/ruby/2.0.0/gems/eventmachine-1.0.3-x86-mingw32/lib/eventmachine.rb:187:in `run_machine'
  vendor/bundle/ruby/2.0.0/gems/eventmachine-1.0.3-x86-mingw32/lib/eventmachine.rb:187:in `run'
  vendor/bundle/ruby/2.0.0/gems/thin-1.6.1-x86-mingw32/lib/thin/backends/base.rb:73:in `start'
  vendor/bundle/ruby/2.0.0/gems/thin-1.6.1-x86-mingw32/lib/thin/server.rb:162:in `start'
  vendor/bundle/ruby/2.0.0/gems/thin-1.6.1-x86-mingw32/lib/thin/controllers/controller.rb:87:in `start'
  vendor/bundle/ruby/2.0.0/gems/thin-1.6.1-x86-mingw32/lib/thin/runner.rb:200:in `run_command'
  vendor/bundle/ruby/2.0.0/gems/thin-1.6.1-x86-mingw32/lib/thin/runner.rb:156:in `run!'
  vendor/bundle/ruby/2.0.0/gems/thin-1.6.1-x86-mingw32/bin/thin:6:in `<top (required)>'
  bin/thin:16:in `load'
  bin/thin:16:in `<main>'
```

**Comment by two-pack** [comment]
```
ActionController::RoutingError (No route matches [GET] "/redmine/projects/tester-123abc123-12/issues_xls_export_current"):
```

The reason of error is what routing path includes _/redmine_.
I don't know why your environment has above condition.
Is related following post?
https://community.bitnami.com/t/not-able-to-run-redmine-via-thin-service-directly/28780/4

Please check your environment.
If routing path includes _/redmine_ is BitNami default, I think about adding that route in route.rb.
But I haven't BitNami environment on Windows enough so its difficult for me to implement and check it :(

**Comment by mags1225** [comment]
I have it working now. Bitnami default is **/redmine**

For anyone else that has this problem, this is exactly what I did to fix the issue with Bitnami Redmine 3.0.3

Edit the following file:
**c:\bitnami\redmine-3.0.3-0\apps\redmine\scripts\serviceinstall.bat**

Remove `-a 127.0.0.1 --prefix /redmine` from redmineThin1 and RedmineThin2 lines

Open CMD prompt with admin rights
Run following commands

```
cd c:\bitnami\redmine-3.0.3-0\apps\redmine\scripts\
serviceinstall.bat REMOVE
```

CMD prompt will close automatically
Open CMD prompt with admin rights again
Run following commands

```
cd c:\bitnami\redmine-3.0.3-0\apps\redmine\scripts\
serviceinstall.bat INSTALL
```

Edit **C:\Bitnami\redmine-3.0.3-0\apps\redmine\conf\httpd-prefix.conf**

Change this

```
ProxyPass /redmine balancer://redminecluster
ProxyPassReverse /redmine balancer://redminecluster
```

To this

```
ProxyPass / balancer://redminecluster
ProxyPassReverse / balancer://redminecluster
```

Then finally edit this file **C:\Bitnami\redmine-3.0.3-0\apps\redmine\htdocs\config\additional_environment.rb**

Change this

```
config.action_controller.relative_url_root = '/redmine'
```

To This

```
config.action_controller.relative_url_root = ''
```

**Restart all services.**

Redmine is accessible from http://localhost:3001 or http://localhost:3002 at this point and redmine_xls_export is working without any issues.

**Comment by two-pack** [comment]
I fixed to create links in issues page which use relative_url_root.
I checked with BitNami Redmine 3.0.3 on OS X.

**Comment by two-pack** [comment]
When first fix, I removed to use relative_url_root for links. Its ok on BitNami Redmine, but other environment which are on sub-uri like #94 .
I re-fix this problem with referencing http://www.redmine.org/issues/19024 .
