### ISSUE TITLE
Textilizable HTML output

### ISSUE THREAD

**Issue by monakov-y** [two-pack/redmine_xls_export#95]
redmine_xls_export plugin has "Strip HTML" option.

It would be nice if there was an opposite option - textilize all output. So all fields and journal entries would be exported as they are in the views (with textile and macros expanded to HTML).

PS. `Redmine::WikiFormatting.to_html` does the trick, but without macros and redmine internal links expanded. I've also experimented with `textilizable` method, but I can't even call it properly (I am embedded C/C++ programmer and RoR blows up my brain :)

**Comment by two-pack** [comment]
Sorry I don't plan to implement new feature in this plugin.
But welcome to contribute it by all :)

**Comment by monakov-y** [comment]
Would you be so kind to help me with textilizable method. I've modified line 318 and below in lib/xls_export.rb:

``` ruby
when :description
  descr_str = strip_html(issue.description, options).to_s
  textilizable(descr_str)
```

And the production.log says:

```
NoMethodError (undefined method `h' for #<XlsExportController:0xb23d3008>):
  lib/redmine/wiki_formatting/macros.rb:45:in `rescue in exec_macro'
  lib/redmine/wiki_formatting/macros.rb:36:in `exec_macro'
  app/helpers/application_helper.rb:983:in `block in inject_macros'
  app/helpers/application_helper.rb:977:in `gsub!'
  app/helpers/application_helper.rb:977:in `inject_macros'
  app/helpers/application_helper.rb:626:in `parse_non_pre_blocks'
  app/helpers/application_helper.rb:603:in `textilizable'
```

I think it is somehow connected with templates/views. So what should I do to call this method correctly?

**Comment by two-pack** [comment]
What version do you use, Redmine and the plugin?

**Comment by monakov-y** [comment]
We are using Redmine 2.6.0 (Bitnami stack) and lates redmine_xls_export from `features` branch (c35d4e8).

**Comment by two-pack** [comment]
> Would you be so kind to help me with textilizable method. I've modified line 318 and below in lib/xls_export.rb:

I tried to add above lines in xls_export.rb, but I cannot reproduce the problem.
My environment is Redmine 2.6.0 (not BitNami) and 3.0.3 (BitNami).

Is your changing ONLY above code? If you fork this repository and commit your changing, I can try it (but probably not soon).
Can you show me your data to occur the error like Description text, how to make issue, and so?

**Comment by monakov-y** [comment]
Sorry for the late answer.

> Is your changing ONLY above code?

Yes, only this code (in :description case) on top of `features` branch.

> I tried to add above lines in xls_export.rb, but I cannot reproduce the problem.

You can place any macro in the description and it will cause internal error with the message above. For example - reference to the issue (e.g. #123). Descriptions that do not contain any macros are exported perfectly.

**Comment by two-pack** [comment]
Please show me detail steps to
reproduce it and your expected result.

**Comment by two-pack** [comment]
I expect detail steps include concrete dfscription value, input and output.

**Comment by monakov-y** [comment]
> I expect detail steps include concrete dfscription value, input and output.

For example if I have description field (in newly created issue `#123` with subject `Test`):

`Test description of issue #123`

I am expecting this output (like in corresponding `<div>` section inside browser):

``` html
<p>
    Test description of issue
    <a href="/issues/123" class="issue tracker-3 status-1 priority-4 priority-default" title="Test (New)">#123</a>
</p>
```

So the `#123` redmine macro is expanded to the real issue link. Of course, class attribute of the <a> tag could differ depending on your default tracker, status and priority.

**Comment by two-pack** [comment]
I can reproduce it, but I don't know to get your expected result, sorry.

**Comment by monakov-y** [comment]
Thank you anyway. I'll ask on redmine forums.

**Comment by two-pack** [comment]
This repository is archived. See #135.
