### ISSUE TITLE
Support permission option for specific roles to export xls only

### ISSUE THREAD

**Issue by fon1105** [two-pack/redmine_xls_export#96]
Would it be possible to support permission option for specific roles to export xls only?

Thanks for your response.

**Comment by two-pack** [comment]
Sorry I don't plan to implement new feature in this plugin.
But welcome to contribute it by all :)

**Comment by fon1105** [comment]
Noted with thanks :)

**Comment by two-pack** [comment]
This repository is archived. See #135.
